---
sidebar: sidebar 
permalink: integrations/dashboard-overview.html 
keywords: Keystone, Digital Advisor, keystone-aiq, aiq, BlueXP, Keystone dashboard, NetApp Console, Console 
summary: Como suscriptor de NetApp Keystone STaaS, puede obtener una descripción general de sus suscripciones desde NetApp Console o Digital Advisor. 
---
= Obtenga más información sobre el panel de control de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El panel de control de Keystone es su solución ideal para supervisar, analizar y gestionar eficazmente sus suscripciones de Keystone. A través del panel de control de Keystone, puede lograr los siguientes objetivos:

* *Supervisa los detalles de las suscripciones*: Mira información detallada sobre tus suscripciones a Keystone, incluidos los niveles de servicio de rendimiento (servicios base y complementarios como la protección avanzada de datos y Data Infrastructure Insights), el uso de capacidad, los activos y las alertas.
* *Realice un seguimiento del uso de la capacidad y genere informes*: realice un seguimiento del uso de la capacidad actual e histórico y genere informes para analizar los datos de suscripción y tomar decisiones informadas.
* *Ver cronograma de suscripciones*: Manténgase informado sobre fechas y eventos clave monitoreando el cronograma de sus suscripciones.
* *Administrar suscripciones*: envíe solicitudes para modificar los niveles de rendimiento del servicio u otros parámetros de suscripción a medida que cambien sus necesidades.
* *Analizar volúmenes y objetos*: obtenga información detallada sobre los volúmenes y objetos de sus suscripciones, incluida su capacidad tanto a nivel de volumen como de objeto.




== Acceda al panel de control de Keystone

Puede acceder al panel de control de Keystone a través de:

* *Consola de NetApp *: acceda al panel desde *Almacenamiento > Keystone > Descripción general* en la consola. Para obtener más información, consultelink:../integrations/keystone-console.html["Panel de control de Keystone en la consola de NetApp"^] .
* *Asesor digital Active IQ* (también conocido como Asesor digital): acceda al panel desde *General > Suscripciones Keystone* en Asesor digital. Para obtener más información, consulte link:../integrations/keystone-aiq.html["Panel de control de Keystone en Digital Advisor"^].




== Acerca de la consola de NetApp

Se puede acceder a Keystone a través de la consola NetApp .

La consola de NetApp proporciona una gestión centralizada de los servicios de datos y almacenamiento de NetApp en entornos locales y en la nube a escala empresarial. La consola es necesaria para acceder y utilizar los servicios de datos de NetApp . Como interfaz de administración, le permite administrar muchos recursos de almacenamiento desde una sola interfaz. Los administradores de la consola pueden controlar el acceso al almacenamiento y los servicios para todos los sistemas dentro de la empresa.

No necesita una licencia o suscripción para comenzar a usar la consola y solo incurre en cargos cuando necesita implementar agentes de la consola en su nube para garantizar la conectividad con sus sistemas de almacenamiento o servicios de datos de NetApp . Sin embargo, algunos servicios de datos de NetApp accesibles desde la consola requieren licencia o suscripción.

Obtenga más información sobre ellink:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Consola de NetApp"^] .

Tenga en cuenta lo siguiente:

* Si bien la consola y el Digital Advisor ofrecen algunas funciones exclusivas, la consola proporciona funcionalidad administrativa para Keystone, lo que le permite administrar suscripciones y realizar los ajustes necesarios. Para obtener más información, consulte link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-keystone-roles.html["Roles de acceso de Keystone en la NetApp Console"^].
* Digital Advisor está integrado con la consola, lo que le permite acceder a todas las funciones de Digital Advisor , incluido el panel de Keystone , directamente desde la consola. Para obtener más información, consultelink:https://docs.netapp.com/us-en/active-iq/digital-advisor-integration-with-console.html#netapp-console["Integración de Digital Advisor con la consola de NetApp"^] .




== Funciones Keystone en NetApp Console y Digital Advisor

La siguiente tabla muestra la disponibilidad de funciones en NetApp Console y Digital Advisor, lo que le ayudará a identificar rápidamente la plataforma adecuada para sus necesidades:

|===


| *Característica* | * Consola NetApp * | *Asesor Digital* 


 a| 
link:../integrations/subscriptions-tab.html["Ver los detalles de su suscripción"]
| Sí | Sí 


 a| 
link:../integrations/current-usage-tab.html["Supervisar el uso actual e histórico de la capacidad"]
| Sí | Sí 


 a| 
link:../integrations/subscription-timeline.html["Seguimiento del cronograma de suscripción"]
| Sí | No 


 a| 
link:../integrations/assets-tab.html["Ver activos asociados con una suscripción de Keystone"]
| Sí | Sí 


| link:../integrations/assets.html["Ver activos en múltiples suscripciones de Keystone"] | Sí | No 


 a| 
link:../integrations/monitoring-alerts.html["Ver y administrar alertas y monitores"]
| Sí | No 


 a| 
link:../integrations/options.html#generate-reports-from-netapp-console-or-digital-advisor["Generar informes"]
| Sí | Sí 


 a| 
link:../integrations/volumes-objects-tab.html["Ver detalles de volúmenes y objetos"]
| Sí | Sí 


 a| 
link:../integrations/adp-tab.html["Ver el consumo y la salud de MetroCluster"]
| Sí (incluye estado de salud, vista de topología y monitoreo de sincronización) | Sí (solo datos de consumo) 


 a| 
link:../integrations/performance-tab.html["Ver métricas de rendimiento"]
| No | Sí 
|===
*Información relacionada*

* link:../integrations/dashboard-access.html["Comience a utilizar el panel de control de Keystone"]
* link:../integrations/keystone-console.html["Panel de control de Keystone en la consola de NetApp"]
* link:..//integrations/keystone-aiq.html["Panel de control de Keystone en Digital Advisor"]

