---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Si compraste un servicio de nube con tu suscripción a NetApp Keystone, puedes acceder a esos servicios y gestionarlos mediante BlueXP. 
---
= Más información sobre Keystone y BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BlueXP de NetApp es un único plano de control para crear, proteger y gobernar datos en tus entornos on-premises y de nube. Si compras un servicio de nube en tu suscripción a NetApp Keystone, puedes acceder a esos servicios y gestionarlos a través de BlueXP.

El panel del asesor digital de BlueXP te proporciona una vista gráfica y funcionalidades en profundidad para supervisar el uso de tu suscripción a Keystone y generar informes. Si desea obtener más información sobre la consola del asesor digital y Keystone, consulte link:../integrations/aiq-keystone-details.html["Panel de suscripción de Keystone e informes"].

Como cliente de Keystone, si tiene suscripción a Cloud Volumes ONTAP, puede usar los servicios de Keystone para cobrar el uso de Cloud Volumes ONTAP y ver los detalles de facturación y consumo a través de BlueXP.

Para ello, debe crear una o más cuentas de BlueXP y vincularlas con su cuenta de Keystone. Mientras adquiere un servicio cloud a través de Keystone, debe proporcionar los detalles de sus cuentas de BlueXP a su Keystone Success Manager (KSM). De este modo, es posible medir y cobrar correctamente el uso de los servicios cloud a través de su suscripción de Keystone.

Para obtener más información sobre Keystone y BlueXP, consulte los siguientes enlaces en los documentos de BlueXP:

* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#keystone-flex-subscription["Suscripción a Keystone"^]
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-keystone.html["Gestione suscripciones de Keystone"^]

