---
sidebar: sidebar 
permalink: integrations/keystone-cm.html 
keywords: Keystone-BlueXP 
summary: Keystone y BlueXP 
---
= Keystone y BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp BlueXP es una plataforma completa para supervisar cientos de fuentes de datos y cuenta con su propio panel de visualización interactivo. Si compras un servicio de nube en tu suscripción a NetApp Keystone, puedes acceder a esos servicios y gestionarlos a través de BlueXP.

El panel del asesor digital de BlueXP te proporciona una vista gráfica y funcionalidades en profundidad para supervisar el uso de tu suscripción a Keystone y generar informes. Si desea obtener más información sobre la consola del asesor digital y Keystone, consulte link:../integrations/aiq-keystone-details.html["Panel de suscripción de Keystone e informes"].

Como cliente de Keystone, si tiene suscripción a Cloud Volumes ONTAP, puede usar los servicios de Keystone para cobrar el uso de Cloud Volumes ONTAP y ver los detalles de facturación y consumo a través de BlueXP.

Para ello, debe crear una o más cuentas de BlueXP y vincularlas con su cuenta de Keystone. Mientras adquiere un servicio cloud a través de Keystone, debe proporcionar los detalles de sus cuentas de BlueXP a su Keystone Success Manager (KSM). De este modo, es posible medir y cobrar correctamente el uso de los servicios cloud a través de su suscripción de Keystone.

Para obtener más información sobre Keystone y BlueXP, consulte los siguientes enlaces en los documentos de BlueXP:

* https://["Suscripción a Keystone"^]
* https://["Gestione suscripciones de Keystone"^]

