---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de Keystone
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades en STaaS de Keystone
      url: "/release-notes/whats-new.html"
    - title: Problemas solucionados
      url: "/release-notes/fixed-issues.html"
    - title: Limitaciones conocidas
      url: "/release-notes/known-limitations.html"
    - title: Problemas conocidos
      url: "/release-notes/known-issues.html"
  - title: Le damos la bienvenida a Keystone
    url: "/concepts/overview.html"
  - title: Configure y configure Keystone
    entries:
    - title: Qué es Keystone Collector
      url: "/installation/installation-overview.html"
    - title: Prepara tu sistema para instalar Keystone Collector
      entries:
      - title: Requisitos de vSphere de VMware
        url: "/installation/vapp-prereqs.html"
      - title: Requisitos de Linux
        url: "/installation/linux-prereqs.html"
      - title: Requisitos de ONTAP y StorageGRID
        url: "/installation/addl-req.html"
    - title: Instale Keystone Collector
      entries:
      - title: Puesta en marcha de VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Instalación de Linux
        url: "/installation/linux-installation.html"
      - title: Validación automática de integridad
        url: "/installation/validation.html"
    - title: Configure Keystone Collector
      url: "/installation/configuration.html"
    - title: Supervise el estado del sistema
      url: "/installation/monitor-health.html"
    - title: Actualiza Keystone Collector
      url: "/installation/upgrade.html"
    - title: Configura AutoSupport para Keystone
      url: "/installation/asup-config.html"
    - title: Datos recopilados para facturación
      url: "/installation/data-collection.html"
  - title: Sáquele más partido a los servicios de Keystone
    entries:
    - title: Consulta el panel de Keystone en el asesor digital de Active IQ
      url: "/integrations/keystone-aiq.html"
    - title: Consulta de detalles de consumo y generación de informes
      url: "/integrations/aiq-keystone-details.html"
    - title: Gestiona las suscripciones de Keystone desde BlueXP
      url: "/integrations/keystone-cm.html"
  - title: Más información sobre Keystone
    entries:
    - title: Capacidad de almacenamiento admitida
      url: "/concepts/supported-storage-capacity.html"
    - title: Métricas y definiciones
      url: "/concepts/metrics.html"
    - title: Almacenamiento compatible en Keystone
      url: "/concepts/supported-storage-services.html"
    - title: Niveles de servicio en Keystone
      url: "/concepts/service-levels.html"
    - title: Servicios complementarios
      entries:
      - title: Organización en niveles de los datos
        url: "/concepts/data-tiering.html"
      - title: Protección de datos avanzada
        url: "/concepts/adp.html"
      - title: EE. UU Soporte para ciudadanos de EE. UU. (USCS)
        url: "/concepts/uscs.html"
      - title: Componentes no retornables, no volátiles y cumplimiento de SnapLock
        url: "/concepts/nrnvc.html"
      - title: Keystone y Equinix
        url: "/concepts/equinix.html"
  - title: Más información acerca de los niveles de servicio
    entries:
    - title: Calidad de servicio
      url: "/concepts/qos.html"
    - title: Requisitos de capacidad para niveles de servicio
      url: "/concepts/capacity-requirements.html"
    - title: Acuerdo de nivel de servicio sostenible
      url: "/concepts/sla-sustainability.html"
  - title: Facturación
    entries:
    - title: Precios Keystone
      url: "/concepts/pricing.html"
    - title: Facturación basada en la capacidad comprometida
      url: "/concepts/committed-capacity-billing.html"
    - title: Medición basada en la capacidad consumida
      url: "/concepts/consumed-capacity-billing.html"
    - title: Facturación basada en consumo en ráfaga
      url: "/concepts/burst-consumption-billing.html"
    - title: Facturación basada en diversos tipos de volumen
      url: "/concepts/misc-volume-billing.html"
    - title: Horarios de facturación
      url: "/concepts/billing-schedules.html"
  - title: Entornos operados por partners y clientes
    url: "/concepts/operational-models.html"
  - title: Infraestructura Keystone
    entries:
    - title: Detalles de la infraestructura
      url: "/concepts/infra.html"
    - title: Componentes
      url: "/concepts/components.html"
    - title: Flujo de datos
      url: "/concepts/data-flow.html"
  - title: Centro de soporte de servicios globales de NetApp
    url: "/concepts/gssc.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: "¿Qué es NetApp Keystone?"
      url: "/concepts/overview.html"
    - title: Instalación de Keystone Collector en VMware vSphere
      url: "/installation/vapp-installation.html"
    - title: Instalación de Keystone Collector en Linux
      url: "/installation/linux-installation.html"
    - title: Vea su uso en el asesor digital
      url: "/integrations/keystone-aiq.html"
    - title: Genera informes de tu consumo
      url: "/integrations/aiq-keystone-details.html"
  - title: Servicios compatibles en Keystone
    links:
    - title: Niveles de servicio de Keystone
      url: "/concepts/service-levels.html"
    - title: Calidad de servicio (QoS)
      url: "/concepts/qos.html"
    - title: "¿Cuáles son las unidades de medida?"
      url: "/concepts/metrics.html"
    - title: "¿Qué es el almacenamiento base compatible?"
      url: "/concepts/supported-storage-services.html"
    - title: "¿Puedo reasignar mi gasto de las instalaciones a la nube?"
      url: "/concepts/capacity-requirements.html#capacity-adjustments"
  - title: Precios y facturación de Keystone
    links:
    - title: Conoce los precios de Keystone
      url: "/concepts/pricing.html"
    - title: Mis horarios de facturación
      url: "/concepts/billing-schedules.html"
    - title: Facturación basada en la capacidad comprometida
      url: "/concepts/committed-capacity-billing.html"
    - title: Medición basada en la capacidad consumida
      url: "/concepts/consumed-capacity-billing.html"
    - title: "¿Qué sucede si he consumido más que mi capacidad comprometida?"
      url: "/concepts/burst-consumption-billing.html"
  - title: Sáquele más partido a los servicios de Keystone
    links:
    - title: Conozca a su equipo de soporte (Keystone GSSC)
      url: "/concepts/gssc.html"
    - title: "¿Qué puedo hacer con mis datos inactivos o menos utilizados?"
      url: "/concepts/data-tiering.html"
    - title: "¿Cómo puedo proteger mis datos de Keystone?"
      url: "/concepts/adp.html"
    - title: Keystone y BlueXP
      url: "/integrations/keystone-cm.html"
    - title: Soporte de ciudadanos de EE. UU
      url: "/concepts/uscs.html"
  - title: Más información
    links:
    - title: Suscripciones de Keystone versión 1 (anteriormente, suscripciones a Keystone
        Flex)
      url: https://docs.netapp.com/us-en/keystone/
    - title: Asesor digital de Active IQ
      url: https://docs.netapp.com/us-en/active-iq/index.html
    - title: BlueXP
      url: https://docs.netapp.com/us-en/cloud-manager-family/
    - title: Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/
