---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de Keystone
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades en STaaS de Keystone
      url: "/release-notes/whats-new.html"
    - title: Problemas solucionados
      url: "/release-notes/fixed-issues.html"
    - title: Problemas conocidos
      url: "/release-notes/known-issues.html"
    - title: Limitaciones conocidas
      url: "/release-notes/known-limitations.html"
  - title: Más información sobre Keystone
    entries:
    - title: Descripción general
      url: "/concepts/overview.html"
    - title: Infraestructura Keystone
      url: "/concepts/infra.html"
    - title: Componentes
      url: "/concepts/components.html"
    - title: Flujo de datos
      url: "/concepts/data-flow.html"
    - title: Modelos operativos
      url: "/concepts/operational-models.html"
    - title: Recopilador Keystone
      url: "/installation/installation-overview.html"
  - title: Configure y configure Keystone
    entries:
    - title: Requisitos
      entries:
      - title: VSphere de VMware
        url: "/installation/vapp-prereqs.html"
      - title: Linux
        url: "/installation/linux-prereqs.html"
      - title: ONTAP y StorageGRID
        url: "/installation/addl-req.html"
    - title: Instale Keystone Collector
      entries:
      - title: Ponga en marcha sus operaciones en VMware vSphere
        url: "/installation/vapp-installation.html"
      - title: Instalar en Linux
        url: "/installation/linux-installation.html"
      - title: Validar integridad
        url: "/installation/validation.html"
    - title: Configure Keystone Collector
      url: "/installation/configuration.html"
    - title: Configure AutoSupport
      url: "/installation/asup-config.html"
    - title: Seguridad de Keystone Collector
      url: "/installation/security.html"
    - title: Datos recopilados para facturación
      url: "/installation/data-collection.html"
  - title: Supervisión y actualización
    entries:
    - title: Supervise el estado del sistema
      url: "/installation/monitor-health.html"
    - title: Actualiza Keystone Collector
      url: "/installation/upgrade.html"
  - title: Consola de Keystone
    entries:
    - title: Consulta el panel de Keystone
      url: "/integrations/keystone-aiq.html"
    - title: Consulta de detalles de uso y generación de informes
      url: "/integrations/aiq-keystone-details.html"
    - title: Pestaña Suscripciones
      url: "/integrations/subscriptions-tab.html"
    - title: Pestaña Uso actual
      url: "/integrations/current-usage-tab.html"
    - title: Pestaña Capacity Trend
      url: "/integrations/capacity-trend-tab.html"
    - title: Pestaña Volumes & Objects
      url: "/integrations/volumes-objects-tab.html"
    - title: Pestaña Rendimiento
      url: "/integrations/performance-tab.html"
    - title: Activos
      url: "/integrations/assets-tab.html"
    - title: Gestiona las suscripciones de Keystone desde BlueXP
      url: "/integrations/keystone-cm.html"
  - title: Servicios Keystone STaaS
    entries:
    - title: Métricas y definiciones
      url: "/concepts/metrics.html"
    - title: Calidad de servicio
      url: "/concepts/qos.html"
    - title: Almacenamiento admitido
      url: "/concepts/supported-storage-services.html"
    - title: Capacidad admitida
      url: "/concepts/supported-storage-capacity.html"
    - title: Niveles de servicio
      url: "/concepts/service-levels.html"
    - title: Capacidad admitida para niveles de servicio
      url: "/concepts/capacity-requirements.html"
    - title: Servicios de suscripción de Keystone versión 1
      url: "/subscription-services-v1.html"
    - title: Servicios complementarios
      entries:
      - title: Protección de datos avanzada
        url: "/concepts/adp.html"
      - title: Organización en niveles de los datos
        url: "/concepts/data-tiering.html"
      - title: Servicios con tecnología Equinix
        url: "/concepts/equinix.html"
      - title: Componentes no retornables, no volátiles y cumplimiento de SnapLock
        url: "/concepts/nrnvc.html"
      - title: EE. UU Soporte para ciudadanos de EE. UU. (USCS)
        url: "/concepts/uscs.html"
  - title: Facturación
    entries:
    - title: Precios Keystone
      url: "/concepts/pricing.html"
    - title: Facturación basada en la capacidad comprometida
      url: "/concepts/committed-capacity-billing.html"
    - title: Medición basada en la capacidad consumida
      url: "/concepts/consumed-capacity-billing.html"
    - title: Facturación basada en consumo en ráfaga
      url: "/concepts/burst-consumption-billing.html"
    - title: Facturación basada en diversos tipos de volumen
      url: "/concepts/misc-volume-billing.html"
    - title: Horarios de facturación
      url: "/concepts/billing-schedules.html"
  - title: Centro de soporte de servicios globales de NetApp
    url: "/concepts/gssc.html"
  - title: Avisos legales
    url: "/legal-notices.html"
