= Por encima de la capacidad de ráfaga en el gráfico de consumo histórico
:allow-uri-read: 


Nuevas mejoras en el panel de Keystone en la NetApp Console:



=== Por encima de la capacidad de ráfaga en el gráfico de consumo histórico

El gráfico de consumo histórico de la pestaña *Tendencia de consumo* ahora resalta el uso que supera el límite de ráfagas. Para obtener más información, consulta link:./integrations/consumption-tab.html["Vea las tendencias de consumo de sus suscripciones a Keystone"].



=== Previsión de uso de la capacidad

Puedes usar la opción *Previsión* en la vista *Consumo histórico* de la pestaña *Tendencia de consumo* para proyectar el uso de capacidad durante los próximos 120 días a partir de la fecha actual. Para saber más, consulta link:./integrations/consumption-tab.html#view-forecast-data["Ver datos de previsión"].



=== ID de seguimiento en la exportación de suscripciones

El informe de suscripciones descargado de la página *Suscripciones* ahora incluye el *ID de seguimiento* en los datos de nivel de servicio de rendimiento para los formatos Excel y CSV.



=== Actualizaciones de la visibilidad de la columna de la página Subscriptions

En la página *Suscripciones*, la columna *Keystone version* ahora está oculta por defecto y la columna *Linked subscriptions* solo aparece cuando hay suscripciones vinculadas disponibles.
