---
sidebar: sidebar 
permalink: concepts/billing-schedules-v2.html 
keywords: billing schedules, schedule for payment 
summary: Las suscripciones a Keystone STaaS se facturan mensualmente y anualmente. 
---
= Horarios de facturación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las suscripciones de Keystone STaaS en la versión 2 (v2) se facturan de forma mensual o anual.



== Facturación mensual

Las facturas se envían mensualmente. Para el mes en el que se han hecho los servicios, se enviará una factura el mes siguiente. Por ejemplo, la factura de los servicios que ha utilizado en enero se entrega a principios de febrero. Esta factura incluye los cargos por la capacidad comprometida y, si corresponde, cualquier uso de ráfaga.



== Facturación anual

Al principio de cada año de suscripción se genera una factura por el pago mínimo de la capacidad comprometida. Se genera en la fecha de inicio de la suscripción. Al final de un trimestre de suscripción se envía otra factura, en la que se suman los cargos aplicables de cualquier uso de ráfaga acumulado en ese trimestre. Si la capacidad comprometida cambia durante una suscripción, se enviará una factura el mismo día por los pagos mínimos prorrateados por el resto de ese año de suscripción. La facturación se calcula a partir del día en que el cambio en la capacidad comprometida es efectivo.
