---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Las suscripciones de Keystone STaaS se facturan de forma mensual, trimestral, semestral o anual. 
---
= Obtenga más información sobre los cronogramas de facturación de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las suscripciones de Keystone STaaS se facturan de forma mensual, trimestral, semestral o anual.



== Facturación mensual

Las facturas se envían mensualmente. Para el mes en el que se han hecho los servicios, se enviará una factura el mes siguiente. Por ejemplo, la factura de los servicios que ha utilizado en enero se entrega a principios de febrero. Esta factura incluye los cargos por la capacidad comprometida y, si corresponde, cualquier uso de ráfaga.



== Facturación trimestral, semestral y anual

Para la facturación trimestral, semestral y anual, el proceso es similar con ligeras variaciones en los tiempos:

* *Facturación trimestral*: Se genera una factura al inicio de cada trimestre de suscripción por el pago mínimo de la capacidad comprometida. Se envía otra factura al final del trimestre por cualquier aumento repentino de consumo.
* *Facturación semestral*: Se genera una factura a principios de cada seis meses por el pago mínimo de la capacidad comprometida.  Al final de cada trimestre se envía otra factura por cualquier exceso de uso acumulado.
* *Facturación anual*: Al inicio de cada año de suscripción se genera una factura por el pago mínimo de la capacidad comprometida.  Al final de cada trimestre se envía otra factura por cualquier exceso de uso acumulado.


Para la facturación trimestral, semestral y anual, si la capacidad comprometida se modifica durante una suscripción, se envía una factura el mismo día por los pagos mínimos prorrateados por el resto de ese año de suscripción.  La facturación se calcula a partir del día en que se hace efectivo el cambio en la capacidad comprometida.
