---
sidebar: sidebar 
permalink: concepts/billing-schedules.html 
keywords: billing schedules, schedule for payment 
summary: Las suscripciones a Keystone STaaS se facturan mensualmente y anualmente. 
---
= Horarios de facturación
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las suscripciones de Keystone STaaS en la versión 3 (v3) se facturan de forma mensual, trimestral, semestral o anual.



== Facturación mensual

Las facturas se envían mensualmente. Para el mes en el que se han hecho los servicios, se enviará una factura el mes siguiente. Por ejemplo, la factura de los servicios que ha utilizado en enero se entrega a principios de febrero. Esta factura incluye los cargos por la capacidad comprometida y, si corresponde, cualquier uso de ráfaga.



== Facturación trimestral, semestral y anual

Para la facturación trimestral, semestral y anual, el proceso es similar con ligeras variaciones en los tiempos:

* *Facturación trimestral*: Se genera una factura al inicio de cada trimestre de suscripción por el pago mínimo de la capacidad comprometida. Se envía otra factura al final del trimestre por cualquier aumento repentino de consumo.
* *Facturación semestral*: Se genera una factura al inicio de cada semestre por el pago mínimo de la capacidad comprometida. Se envía otra factura al final de cada trimestre por cualquier exceso de consumo acumulado.
* *Facturación anual*: Se genera una factura al inicio de cada año de suscripción por el pago mínimo de la capacidad comprometida. Se envía otra factura al final de cada trimestre por cualquier aumento repentino de consumo.


Para la facturación trimestral, semestral y anual, si la capacidad comprometida se modifica durante una suscripción, se envía una factura el mismo día por los pagos mínimos prorrateados por el resto de ese año de suscripción. La facturación se calcula a partir del día en que el cambio en la capacidad comprometida es efectivo.
