---
sidebar: sidebar 
permalink: concepts/components.html 
keywords: infrastructure component, deployment requirement, installation requirement 
summary: Obtenga información sobre los componentes necesarios para habilitar los servicios de STaaS de NetApp Keystone en su entorno. 
---
= Componentes necesarios para los servicios de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Necesita varios componentes para habilitar los servicios NetApp Keystone STaaS. Revise estos componentes antes de comenzar.



== Los requisitos del centro

Existen algunos requisitos específicos de cada sitio, como el espacio, los racks, las PDU, la energía, y la refrigeración, y aquí se tratan requisitos de seguridad y red adicionales.



=== Espacio

Espacio físico para alojar el equipo de infraestructura de Keystone (a disposición de los clientes). NetApp proporciona las especificaciones de peso basadas en la configuración final.



=== Racks

Cuatro bastidores de poste en la oferta operada por el cliente (a ser proporcionados por los clientes). En la oferta dirigida por NetApp, NetApp o el cliente pueden proporcionar los racks, en función de sus necesidades. NetApp proporciona 42 racks de profundidad.



=== PDU

Debe proporcionar las unidades de distribución de energía (PDU) conectadas a dos circuitos protegidos separados con suficientes tomas C13. En la oferta dirigida por el cliente, en algunos casos se requieren tomas C19. En la oferta gestionada por NetApp, NetApp o el cliente pueden proporcionar estas PDU, según unos requisitos.



=== Potencia

Debe proporcionar la alimentación necesaria. NetApp le proporcionará las especificaciones de los requisitos de alimentación en función de la clasificación de 200 V (Normalmente A, máximo A, W típico, máximo W, tipo de cable de alimentación, y cantidad), en función de la configuración final. Todos los componentes tienen fuentes de alimentación redundantes. NetApp proporcionará los cables de alimentación dentro del armario.



=== Refrigeración

NetApp puede proporcionar las especificaciones de requisitos de refrigeración (BTU típico, BTU máximo) en función de la configuración y los requisitos finales.



=== Equipos virtuales

Las máquinas virtuales son necesarias para la implementación de Keystone Collector y ITOM Collector. Para conocer los requisitos previos de instalación, consulte link:../installation/installation-overview.html["Guía de instalación para Keystone Collector"]y link:../installation/itom-prereqs.html["Requisitos de instalación para ITOM Collector"]. Los otros requisitos se comparten durante la puesta en marcha.



=== Opciones de puesta en marcha

Keystone Collector se puede implementar a través de los siguientes métodos:

* Plantilla OVA de VMware (se requiere VMware vCenter Server 6.7 o posterior)
* El cliente proporciona un servidor Linux que se ejecuta en uno de los siguientes sistemas operativos: Debian 12, Red Hat Enterprise Linux 8.6 o versiones 8.x posteriores, Red Hat Enterprise Linux 9.0 o versiones posteriores, o CentOS 7 (solo para entornos existentes). El software Keystone se instala mediante `.deb` o `.rpm` paquete, dependiendo de la distribución de Linux.


El recopilador de ITOM se puede desplegar mediante los siguientes métodos:

* El cliente proporciona un servidor Linux que se ejecuta en Debian 12, Ubuntu 20.04 LTS, Red Hat Enterprise Linux (RHEL) 8.x, Red Hat Enterprise Linux 9.0, Amazon Linux 2023 o versiones más recientes.
* El cliente proporciona un servidor Windows que ejecute Windows Server 2016 o versiones posteriores.
+

TIP: Los sistemas operativos recomendados son Debian 12, Windows Server 2016 o versiones más recientes.





=== Redes

El acceso saliente a _keystone.NetApp.com_ es necesario para las actualizaciones de software y las cargas de datos de uso, que son esenciales para el funcionamiento y el mantenimiento de la puerta de enlace de la solución Keystone Collector y AIOps.

En función de los requisitos del cliente y de las controladoras de almacenamiento utilizadas, NetApp puede proporcionar conectividad de 10 GB, 40 GB y 100 GB en las instalaciones del cliente.

NetApp proporciona los transceptores necesarios para dispositivos de infraestructura proporcionados por NetApp solamente. Debe proporcionar los transceptores necesarios para dispositivo de cliente y cableado a los dispositivos de infraestructura Keystone proporcionados por NetApp.



== Requisito de acceso remoto

Se requiere conectividad de red entre la infraestructura de almacenamiento instalada en el centro de datos del cliente o en los servicios ubicados conjuntamente por el cliente y el centro de operaciones de Keystone. El cliente es responsable de proporcionar los equipos informáticos y virtuales, así como los servicios de Internet. El cliente también es responsable de la aplicación de parches del sistema operativo (implementaciones no basadas en OVA) y el refuerzo de la seguridad basado en políticas de seguridad internas. El diseño de red debe tener un protocolo seguro y las normativas de firewall serán aprobadas tanto por NetApp como por los clientes.

NetApp debe acceder a los componentes de hardware y software instalados para supervisar y gestionar, y proporcionar servicios como la supervisión y la facturación a los clientes de Keystone. El método más común es establecer una conexión de red privada virtual (VPN) con la red del cliente y acceder a los datos necesarios. Para superar cualquier complejidad operativa que perciban los clientes como consecuencia de la apertura de puertos de firewall a nuevos servicios, las herramientas de supervisión inician una conexión externa. Las aplicaciones en la nube de NetApp, como la solución de supervisión ITOM y Zuora, utilizan esta conexión para realizar sus respectivos servicios. Este método cumple con los requisitos del cliente de no abrir puertos de firewall, aunque proporciona acceso a los componentes de supervisión que forman parte de este servicio.
