---
sidebar: sidebar 
permalink: concepts/consumed-capacity-billing.html 
keywords: consumed capacity billing, billing and consumed capacity 
summary: Facturación basada en la capacidad consumida 
---
= Medición basada en la capacidad consumida
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS mide la capacidad que usted consume durante el uso de los servicios.

La capacidad comprometida es la capacidad comprometida para un nivel de servicio concreto mientras compra la suscripción. La capacidad consumida es la capacidad que realmente usan las cargas de trabajo. Como parte de la puesta en marcha del servicio Keystone, NetApp supervisa y mide de forma continua el consumo del servicio. Cada cinco minutos, el sistema genera un registro de consumo, en el que se detalla la capacidad consumida actualmente para su suscripción. Estos registros se agregan a lo largo del período de facturación para generar facturas e informes de uso.

Si desea obtener información sobre las distintas capacidades compatibles con Keystone, consulte link:../concepts/supported-storage-capacity.html["Capacidades de almacenamiento compatibles con Keystone"].
