---
sidebar: sidebar 
permalink: concepts/data-tiering.html 
keywords: add-on services, add-on, data tiering 
summary: El servicio adicional de organización en niveles identifica los datos que se utilizan con menos frecuencia y los ordena en niveles en el almacenamiento que se da soporte. 
---
= Más información sobre la organización en niveles de los datos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los servicios estándar STaaS de Keystone para almacenamiento de archivos y bloques incluyen funcionalidades de organización por niveles que identifican datos que se usan con menor frecuencia y segmentación para almacenamiento en frío de NetApp compatible con STaaS de Keystone. Puedes utilizar la organización de los datos en niveles como un servicio complementario si deseas organizar los datos inactivos en niveles en cualquier almacenamiento de Keystone que no sea de NetApp ni admita STaaS.

consulte link:../concepts/service-levels.html["Niveles de servicio de rendimiento en Keystone"] .


NOTE: El servicio complementario de niveles solo se requiere cuando los datos están organizados en niveles en cualquier almacenamiento que no sea de NetApp , como Amazon Web Services (AWS) S3, Azure Blob, Google Cloud Platform (GCP) y otros almacenamientos de objetos de terceros compatibles con S3 y compatibles con Keystone STaaS.

La funcionalidad de organización en niveles aprovecha la tecnología FabricPool de NetApp, que permite establecer niveles automatizados de los datos a los que se accede con poca frecuencia en niveles de almacenamiento de objetos tanto dentro como fuera de las instalaciones.

El servicio de niveles de datos complementarios permite la clasificación desde los niveles Extremo, Premium, Rendimiento, Estándar y Valor hasta un destino de almacenamiento de objetos. La proporción de datos calientes y fríos que se deben clasificar no es fija, y cada nivel se mide y factura por separado.

Por ejemplo, si el objetivo del nivel de almacenamiento en frío es:

* Nivel de valor de Keystone STaaS, nivel de objeto StorageGRID de Keystone STaaS o red StorageGRID Webscale (SGWS) existente (propiedad del cliente): no hay ningún cargo adicional; es parte del servicio estándar.
* Cloud público (AWS, Azure, Google) o almacenamiento de objetos de terceros compatible con Keystone STaaS: Hay un coste adicional por capacidad de datos organizados por niveles en objetivos de almacenamiento de datos fríos.


El coste de los servicios de organización en niveles complementarios se aplica a lo largo de todo el período de suscripción.


NOTE: NetApp no proporciona los servicios de red, almacenamiento y computación basados en hiperescalador que requiere Cloud Volumes ONTAP como parte de las suscripciones de Keystone STaaS; estos servicios deben adquirirse directamente de los proveedores de servicios de nube de hiperescalador.

*Información relacionada*

link:https://kb.netapp.com/hybrid/Keystone/AIQ_Dashboard/How_to_approximate_Keystone_Consumption_with_Data_Tiering_(FabricPool)_through_the_ONTAP_cli["Cómo aproximarse al consumo de Keystone con la organización de datos en niveles (FabricPool) con la interfaz de línea de comandos de ONTAP"^]
