---
sidebar: sidebar 
permalink: concepts/gssc.html 
keywords: Keystone support, service request, support ticket 
summary: Si necesita ayuda, póngase en contacto con el Centro de soporte y servicios globales de NetApp. 
---
= Obtén ayuda con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El equipo de soporte de NetApp Keystone y Keystone Success Manager (KSM) son responsables de ofrecerte el servicio para tus suscripciones de Keystone. Si necesitas ayuda, puedes ponerte en contacto con el equipo de soporte de Keystone.



== Soporte de NetApp Keystone

NetApp proporciona servicios operativos de forma remota a clientes de NetApp Keystone. Estos servicios abarcan una amplia gama de disciplinas operativas en distintas actividades de gestión del almacenamiento. Estos servicios incluyen la gestión de activos y configuración, la gestión de la capacidad y el rendimiento, la gestión de cambios, eventos, la gestión de incidentes y problemas, el cumplimiento de solicitudes de servicio y la creación de informes. NetApp demuestra un estado de control y evidencia de apoyo según sea necesario.



== Información adicional

NetApp utiliza la solución de supervisión ITOM para supervisar y conectarse de forma proactiva al entorno de NetApp Keystone para la resolución de problemas.


NOTE: En un modelo operado por un partner, las solicitudes de servicio del inquilino y el subinquilino se asignan al servicio técnico del partner. La herramienta de soporte del partner puede tener integración con la solución ITOM.

Para obtener más información sobre los servicios de Keystone, consulte:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentación de productos de NetApphttps://docs.netapp.com["https://docs.netapp.com"^]




== Supervisión del soporte de Keystone

El soporte de NetApp Keystone supervisa el estado de sus productos y servicios suscritos, ofrece soporte remoto y colabora con su Keystone Success Manager.

.Keystone Success Manager
Keystone Success Manager (KSM) trabaja estrechamente con usted en sus servicios de Keystone y le actualiza con la facturación y los informes operativos semanales o mensuales. Las responsabilidades se especifican en el acuerdo de NetApp Keystone.



== Generando solicitudes de servicio

Durante la incorporación, si se le proporcionaron credenciales para acceder y utilizar ServiceNow de NetApp Keystone, puede usar el portal para generar solicitudes de servicio por problemas relacionados con sus suscripciones de Keystone:

https://netappgssc.service-now.com/csm[]

Asegúrese de tener preparados los detalles del sistema, los registros y la información relacionada antes de elevar la solicitud de servicio. Cuando envía una solicitud de servicio, el equipo de soporte de Keystone recibe el ticket de soporte y accede a la información para solucionar problemas. Puede seguir su ticket de ServiceNow para conocer el estado y la resolución.

Para obtener información sobre cómo añadir paquetes de soporte, consulte link:../installation/monitor-health.html["Genere y recoja el bundle de soporte"].

Si tiene un caso o una incidencia abiertos que debe escalarse, envíe un correo electrónico a una de las siguientes direcciones: keystone.services@netapp.com keystone.escalations@netapp.com
