---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability 
summary: Cálculos de métricas y definiciones de los servicios de Keystone 
---
= Métricas y definiciones utilizadas en los servicios de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los siguientes términos y definiciones se utilizan en el servicio STaaS de NetApp Keystone (Keystone) para medir métricas:

* Unidades de medida de capacidad: Gib, TIB e IB
* Densidad de I/o: IOPS/TIB: Número de operaciones de entrada/salida procesadas por segundo según el espacio total que consume la carga de trabajo, en tebibytes.
* Disponibilidad del servicio
* Durabilidad en un acceso preciso a los datos
* Latencia y velocidad




== Medición de métricas

* * Medición de capacidad en gibibyte (GIB), tebibyte (GIB) y pebebbyte (PIB)*: Mediciones de la capacidad de almacenamiento de datos utilizando base de 1024 (1 GIB = 1024 3 bytes, 1 TIB = 1024 4 bytes y 1 PIB = 1024 TIB 5 bytes).
* * Gráfico de contadores de operaciones en IOPS/TIB*: Las operaciones de protocolo por segundo, solicitadas por la aplicación, divididas por el tamaño del volumen utilizado por las cargas de trabajo.
* *Disponibilidad*: Medido como un porcentaje del número de solicitudes de E/S respondidas con éxito por el servicio, dividido por el número total de solicitudes de E/S realizadas al servicio. Esto se mide en la demarcación del servicio en un mes y no incluye los tiempos de inactividad programados del servicio ni la falta de disponibilidad de las instalaciones, la red u otros servicios proporcionados por el cliente.
* *Durabilidad*: Porcentaje de datos a los que se accede sin pérdida de fidelidad, excluyendo la eliminación o corrupción causada por el cliente.
* *Latencia*: Tiempo de servicio de una solicitud de E/S recibida de un cliente, medido en la demarcación de servicio (puerto de E/S del controlador de almacenamiento).




=== Métricas de rendimiento

Las métricas de rendimiento de rendimiento solo se aplican a los servicios de archivos y bloques en función de:

* Tamaños de bloque de 32 KB
* Combinación de I/o con un 70 % de lectura/30 % de escritura




=== Variaciones en densidad de I/O.

La densidad de I/o calculada en IOPS/TIB y/o Mbps/TIB varía en función de los siguientes factores:

* Características de las cargas de trabajo
* Latencia, excluyendo lo siguiente:
+
** Latencia de las aplicaciones
** Latencia del host
** Latencia en la red del cliente mientras se transfieren datos desde y hacia los puertos de la controladora
** Latencia adicional asociada con la transferencia de datos al almacén de objetos en el caso de FabricPool
** La latencia que aplica calidad de servicio automáticamente para mantener los I/o dentro de los máximos de nivel de servicio


* Los datos de usuario y copia Snapshot que se cuentan como parte de la capacidad utilizada
* Las IOPS mínimas absolutas asignadas en cada volumen ONTAP, independientemente de la cantidad de datos del volumen:
+
** Extrema: 1,000 000 IOPS
** Premium: 500 000 IOPS
** Rendimiento, estándar y valor: 75 000 IOPS


* Mientras se utilizan los servicios complementarios de protección de datos avanzada, la latencia objetivo se aplica únicamente al servicio de las solicitudes de I/o del almacenamiento local.




=== AQoS de volumen

Cada volumen ONTAP debe tener aplicada la política de calidad de servicio adaptativa aplicable. De lo contrario, la capacidad dentro de cada volumen que no tiene una política de AQoS se factura a la tasa del nivel de servicio más alto.
