---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: El servicio de STaaS de NetApp Keystone utiliza varios términos para medir métricas. Es posible que desee obtener más información sobre estos términos a medida que utiliza Keystone para la versión 3 del servicio. 
---
= Métricas y definiciones utilizadas en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El servicio de STaaS de NetApp Keystone utiliza varios términos para medir métricas. Es posible que desee obtener más información sobre estos términos a medida que utiliza Keystone para la versión 3 (v3).

Los siguientes términos y definiciones se utilizan dentro del servicio STaaS de Keystone para medir métricas:

* Unidades de medida de capacidad: Gib, TIB e IB
* IOPS: Número de operaciones de entrada/salida procesadas por segundo.
* Disponibilidad del servicio
* Durabilidad en un acceso preciso a los datos
* Latencia y velocidad




== Medición de métricas

* * Medición de capacidad en gibibyte (GIB), tebibyte (GIB) y pebebbyte (PIB)*: Mediciones de la capacidad de almacenamiento de datos utilizando base de 1024 (1 GIB = 1024 3 bytes, 1 TIB = 1024 4 bytes y 1 PIB = 1024 TIB 5 bytes).
* *Gráfico del contador de operaciones en IOPS*: Las operaciones de protocolo por segundo, solicitadas por la aplicación.
* *Disponibilidad*: Medido como un porcentaje del número de solicitudes de E/S respondidas con éxito por el servicio, dividido por el número total de solicitudes de E/S realizadas al servicio. Esto se mide en la demarcación del servicio en un mes y no incluye el tiempo de inactividad programado del servicio o la falta de disponibilidad de las instalaciones, la red u otros servicios proporcionados por el cliente.
* *Durabilidad*: Porcentaje de datos a los que se accede sin pérdida de fidelidad, excluyendo la eliminación o corrupción causada por el cliente.
* *Latencia*: Tiempo de servicio de una solicitud de E/S recibida de un cliente, medido en la demarcación de servicio (puerto de E/S del controlador de almacenamiento).




=== Métricas de rendimiento

Las siguientes métricas de rendimiento son aplicables para servicios unificados y optimizados por bloques:

*Servicios unificados:*

* *IOPS*: Para ONTAP 9.16.1 con NFS, cada instancia de nivel de rendimiento admite acceso aleatorio con una relación de lectura del 70 % y escritura del 30 %, un tamaño de bloque de 8 KB y una latencia de 1 ms (4 ms para estándar).
* *Rendimiento*: para ONTAP 9.16.1 con NFS, cada instancia de nivel de rendimiento admite acceso secuencial con 100 % de lectura y un tamaño de bloque de 32 KB.


*Bloquear servicios optimizados:*

* *IOPS*: Para ONTAP 9.16.1 con FCP, cada instancia de nivel de rendimiento admite acceso aleatorio con una relación de lectura del 70 % y escritura del 30 %, un tamaño de bloque de 8 KB y una latencia de 1 ms.
* *Rendimiento*: para ONTAP 9.16.1 con FCP, cada instancia de nivel de rendimiento admite acceso secuencial con 100 % de lectura y un tamaño de bloque de 64 KB.

