---
sidebar: sidebar 
permalink: concepts/metrics.html 
keywords: metrics, GiB, IOPS, latency, durability, v3, version 3 
summary: El servicio de STaaS de NetApp Keystone utiliza varios términos para medir métricas. Es posible que desee obtener más información sobre estos términos a medida que utiliza Keystone para la versión 3 del servicio. 
---
= Comprende las métricas y definiciones de almacenamiento en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Conoce los términos clave que Keystone STaaS utiliza para medir e informar sobre tu suscripción de almacenamiento, incluidas las unidades de capacidad, las métricas de rendimiento y las definiciones de disponibilidad.



== Medición de métricas

* *Medición de capacidad en GiB, TiB y PiB*: Mediciones de la capacidad de almacenamiento de datos utilizando la base de 1024 (1 GiB = 1024^3^ bytes, 1 TiB = 1024^4^ bytes y 1 PiB = 1024^5^ bytes).
* *Gráfico del contador de operaciones en IOPS*: Las operaciones de protocolo por segundo, solicitadas por la aplicación.
* *Disponibilidad*: Medido como un porcentaje del número de solicitudes de E/S respondidas con éxito por el servicio, dividido por el número total de solicitudes de E/S realizadas al servicio. Esto se mide en la demarcación del servicio en un mes y no incluye el tiempo de inactividad programado del servicio o la falta de disponibilidad de las instalaciones, la red u otros servicios proporcionados por el cliente.
* *Durabilidad*: Porcentaje de datos a los que se accede sin pérdida de fidelidad, excluyendo la eliminación o corrupción causada por el cliente.
* *Latencia*: Tiempo de servicio de una solicitud de E/S recibida de un cliente, medido en la demarcación de servicio (puerto de E/S del controlador de almacenamiento).

