---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Obtén más información sobre la facturación de Keystone para configuraciones específicas, incluidos volúmenes clonados, protección de datos avanzada, etc. 
---
= Obtenga información sobre la facturación de Keystone para configuraciones de volumen específicas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comprender la facturación de Keystone para configuraciones específicas puede ayudarlo a optimizar el uso del servicio y administrar los costos. Las configuraciones incluyen volúmenes clonados, volúmenes temporales, destinos SnapMirror , LUN y volúmenes de sistema/raíz.



== Facturación de volúmenes clonados

Si los volúmenes se clonan en ONTAP y se los utiliza para realizar un backup y restaurar los datos, puede continuar mediante los clones sin ningún pago adicional. Sin embargo, se cobrarán volúmenes clonados utilizados para cualquier otro fin en el negocio durante un gran período de tiempo.

Tenga en cuenta lo siguiente:

* Los volúmenes clonados no pueden cargarse siempre que su tamaño sea inferior al 10 % del volumen principal (la capacidad física utilizada en el volumen clonado en comparación con la capacidad física utilizada en el volumen principal).
* No existe un período de gracia de 24 horas para los volúmenes clonados. Solo se considera el tamaño del clon.
* Una vez que el volumen clonado supera el 10 % del tamaño físico del volumen principal, el clon se factura como volumen estándar (capacidad utilizada lógica).




== Facturación de volúmenes temporales

Ocasionalmente, ONTAP crea volúmenes temporales (TMP) al mover volúmenes. Estos volúmenes temporales son de corta duración y el consumo en estos volúmenes no se mide para facturación.



== Facturación de destinos de SnapMirror

El precio de los volúmenes de destino de SnapMirror, ya sea para recuperación ante desastres o retención a largo plazo, se basa en el nivel de servicio de rendimiento asignado al destino. No hay cargos adicionales por la protección de datos.



== Facturación para LUN

Para los LUN, la facturación se basa en los niveles de servicio de rendimiento del volumen.



== Volúmenes raíz y del sistema

Los volúmenes raíz y del sistema se supervisan como parte de la supervisión general del servicio de Keystone, pero no se cuentan o se facturan. El consumo en estos volúmenes está exento de facturación.
