---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Billing and miscellaneous scenarios 
summary: Obtén más información sobre la facturación de Keystone para configuraciones específicas, incluidos volúmenes clonados, protección de datos avanzada, etc. 
---
= Escenarios varios para la facturación Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Comprender la facturación de Keystone para configuraciones específicas puede ayudar a optimizar el uso del servicio y gestionar los costes. Los escenarios incluyen volúmenes clonados, protección avanzada de datos, volúmenes temporales, políticas de calidad de servicio, destinos de SnapMirror LUN y volúmenes del sistema/raíz.



== Facturación de volúmenes clonados

Si los volúmenes se clonan en ONTAP y se los utiliza para realizar un backup y restaurar los datos, puede continuar mediante los clones sin ningún pago adicional. Sin embargo, se cobrarán volúmenes clonados utilizados para cualquier otro fin en el negocio durante un gran período de tiempo.

Tenga en cuenta lo siguiente:

* Los volúmenes clonados no pueden cargarse siempre que su tamaño sea inferior al 10 % del volumen principal (la capacidad física utilizada en el volumen clonado en comparación con la capacidad física utilizada en el volumen principal).
* No hay periodo de gracia de 24 horas para los volúmenes clonados, solo se considera el tamaño del clon.
* Una vez que el volumen clonado supera el 10 % del tamaño físico del volumen principal, el clon se factura como volumen estándar (capacidad utilizada lógica).




== Facturación para la protección de datos avanzada

La protección de datos avanzada utiliza NetApp MetroCluster para reflejar datos entre dos clústeres separados físicamente. En los agregados duplicados de MetroCluster, los datos se escriben dos veces una en cada clúster. El servicio de Keystone cobra por el consumo por cada lado de forma independiente, lo que da como resultado dos registros de consumo idénticos. Las tarifas complementarias se aplican a todas las capacidades de la suscripción, independientemente de si los datos están en el origen, o si están reflejados o sin mirroring.

Si supervisa los clústeres a través de System Manager (System Manager) o Active IQ Unified Manager (Unified Manager) de ONTAP, puede que observe una discrepancia entre el consumo informado en estas herramientas y Keystone. System Manager y Unified Manager no notifican volúmenes en un clúster reflejado (remoto); al hacerlo, informa de la mitad de las métricas de consumo que informa el servicio de Keystone.

.Ejemplo:
El centro A y el sitio B se configuran en una configuración de MetroCluster. Cuando un usuario crea un volumen de 10 TB en el sitio A, se crea un volumen idéntico de 10 TB en el sitio B. Keystone identifica 10 TB de consumo en cada sitio, con un incremento total de 20 TB. System Manager y Unified Manager informan de un volumen de 10TB TB creado en el sitio A, pero no notifican un volumen de 10TB GB en el sitio B.

Además, todos los volúmenes creados en un sistema Keystone con protección de datos avanzada se considerarán para el consumo de protección de datos avanzada, independientemente de si esos volúmenes están reflejados o no.



== Facturación de volúmenes temporales

Ocasionalmente, ONTAP crea volúmenes temporales (TMP) al mover volúmenes. Estos volúmenes temporales son de corta duración y el consumo en estos volúmenes no se mide para facturación.



== Facturación y políticas de calidad de servicio adaptativas

Keystone mide el consumo según los niveles de servicio. Cada nivel de servicio está asociado a una política de calidad de servicio (QoS) adaptable específica. Durante la implementación, recibirá un informe de los detalles de cada política de calidad de servicio para los servicios de Keystone que haya suscrito. Durante las operaciones de administración del almacenamiento, asegúrese de que sus volúmenes tengan asignadas políticas de calidad de servicio adecuadas según los niveles de servicio suscritos, para evitar costes inesperados de facturación. Para obtener más información sobre las políticas de calidad de servicio en ONTAP, consulte link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garantice el rendimiento con información general de calidad de servicio"^].



== Facturación de destinos de SnapMirror

El precio del volumen de destino de SnapMirror depende de la política de calidad de servicio para el nivel de servicio asignado en el origen. Sin embargo, si el origen no tiene una política de calidad de servicio asociada, el destino se factura en función del nivel de servicio disponible más bajo.



== Facturación para LUN

Para las LUN, el mismo patrón de facturación se seguido del de los volúmenes regulados por las políticas de calidad de servicio. Si se establecen políticas de calidad de servicio independientes en las LUN, realice lo siguiente:

* El tamaño de la LUN se cuenta para su consumo en función del nivel de servicio asociado de esa LUN.
* El resto del espacio del volumen, si lo hay, se cargará según la política de calidad de servicio del nivel de servicio establecido en el volumen.




== Volúmenes raíz y del sistema

Los volúmenes raíz y del sistema se supervisan como parte de la supervisión general del servicio de Keystone, pero no se cuentan o se facturan. El consumo en estos volúmenes está exento de facturación.
