---
sidebar: sidebar 
permalink: concepts/misc-volume-billing.html 
keywords: Keystone billing, special volume types, cloned volumes, SnapMirror destinations, LUNs, temporary volumes 
summary: Las reglas de facturación de Keystone difieren para determinadas configuraciones de volumen. En esta página se explica la facturación de volúmenes clonados, destinos SnapMirror, LUNs, volúmenes temporales y volúmenes de sistema. 
---
= Facturación Keystone para tipos de volumen específicos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Las reglas de facturación de Keystone difieren para determinadas configuraciones de volumen. Conocer estas excepciones te ayuda a evitar cargos inesperados cuando trabajas con volúmenes clonados, destinos SnapMirror, LUNs o almacenamiento temporal.

La siguiente tabla resume las reglas de facturación para cada tipo de volumen.

[cols="1,2"]
|===
| Tipo de volumen | Norma de facturación 


| Volúmenes clonados | Facturados como volúmenes estándar 


| Volúmenes temporales | No facturado 


| SnapMirror destinos | Facturado según el nivel de servicio de rendimiento de destino 


| LUN | Facturado al nivel de servicio de rendimiento del volumen contenedor 


| Volúmenes raíz y del sistema | Controlado pero no facturado 
|===


== Facturación de volúmenes clonados

Los volúmenes clonados se facturan como volúmenes estándar al mismo nivel de servicio de rendimiento que el volumen del que se clonaron. Todos los volúmenes clonados se miden y facturan independientemente de su tamaño o finalidad.



== Facturación de volúmenes temporales

Ocasionalmente, ONTAP crea volúmenes temporales (TMP) al mover volúmenes. Estos volúmenes temporales son de corta duración y el consumo en estos volúmenes no se mide para facturación.



== Facturación de destinos de SnapMirror

El precio de los volúmenes de destino de SnapMirror, ya sea para recuperación ante desastres o retención a largo plazo, se basa en el nivel de servicio de rendimiento asignado al destino. No hay cargos adicionales por la protección de datos.



== Facturación para LUN

Para los LUN, la facturación se basa en los niveles de servicio de rendimiento del volumen.



== Volúmenes raíz y del sistema

Los volúmenes raíz y del sistema se supervisan como parte de la supervisión general del servicio de Keystone, pero no se cuentan o se facturan. El consumo en estos volúmenes está exento de facturación.
