---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Keystone ofrece un modelo de pago por crecimiento para sus necesidades de consumo flexible y escalable. 
---
= Obtenga más información sobre los precios de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El servicio de suscripción de pago por uso NetApp Keystone STaaS ofrece un consumo flexible y escalable con precios predecibles y por adelantado para sus necesidades de almacenamiento.

Keystone le ofrece las siguientes facilidades de facturación:

* Puede pagar en función de la capacidad comprometida de IOPS y latencia para satisfacer diversas necesidades de carga de trabajo. Los diferentes niveles de servicio de rendimiento (Extreme, Premium, Standard, Value, Object y Cloud Volumes ONTAP) le permiten administrar su almacenamiento en función del nivel de servicio de rendimiento adquirido.
* Presenta una facturación predecible para la capacidad comprometida y el pago por uso de la capacidad variable (en ráfaga).
* Puede seleccionar un precio de paquete para el hardware, el SO principal y el soporte para un precio de $/TIB. Tienes una única factura para cada tipo de almacenamiento, ya sea unificado, en bloques, optimizado, de objetos o servicios de almacenamiento en la nube.
* Puede seleccionar un plazo flexible para los servicios y opciones de pago, como mensual, trimestral, semestral o anual.


La facturación de Keystone se basa en la capacidad comprometida y en el consumo en ráfaga variable.

Si desea obtener información sobre las distintas capacidades compatibles con Keystone, consulte link:../concepts/supported-storage-capacity.html["Capacidades de almacenamiento compatibles con Keystone"].

*Información relacionada*

* link:../concepts/committed-capacity-billing.html["Facturación basada en la capacidad comprometida"]
* link:../concepts/consumed-capacity-billing.html["Medición basada en la capacidad consumida"]
* link:../concepts/burst-consumption-billing.html["Facturación basada en consumo en ráfaga"]
* link:../concepts/misc-volume-billing.html["Facturación basada en diversos tipos de volumen"]
* link:../concepts/billing-schedules.html["Horarios de facturación"]

