---
sidebar: sidebar 
permalink: concepts/pricing.html 
keywords: pricing, billing introduction, Keystone billing 
summary: Precios Keystone 
---
= Precios Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
STaaS de NetApp Keystone permite un precio inicial y predecible para su suscripción de almacenamiento.

Si prefiere el modelo de consumo de gastos operativos (gastos operativos) a gastos de capital o arrendamiento, puede optar por el modelo de pago según crecimiento de Keystone para sus necesidades de consumo flexibles y escalables.

Keystone le ofrece las siguientes instalaciones de facturación:

* Puede pagar según las IOPS y la capacidad comprometida de latencia para satisfacer las necesidades de cargas de trabajo múltiples. Los distintos niveles de servicio de rendimiento: Extreme, Premium, Performance, Standard, Value, Object permite gestionar el almacenamiento en función del nivel de servicio adquirido.
* Presenta una facturación predecible para la capacidad comprometida y el pago por uso de la capacidad variable (en ráfaga).
* Puede seleccionar un precio de paquete para el hardware, el SO principal y el soporte para un precio de $/TIB. Dispone de una única factura para cada tipo de almacenamiento, archivo, bloque, objeto o servicios de almacenamiento en cloud.
* Seleccione un término flexible para los servicios y el pago: Puede optar por 12 meses, 25 TIB o más por sitio. A partir de entonces, puede realizar una renovación automática durante 12 meses.


La facturación de Keystone se basa en la capacidad comprometida y en el consumo en ráfaga variable.

Si desea obtener información sobre las distintas capacidades compatibles con Keystone, consulte link:../concepts/supported-storage-capacity.html["Capacidades de almacenamiento compatibles con Keystone"].

*Información relacionada*

* link:../concepts/committed-capacity-billing.html["Facturación basada en la capacidad comprometida"]
* link:../concepts/consumed-capacity-billing.html["Medición basada en la capacidad consumida"]
* link:../concepts/burst-consumption-billing.html["Facturación basada en consumo en ráfaga"]
* link:../concepts/misc-volume-billing.html["Facturación basada en diversos tipos de volumen"]
* link:../concepts/billing-schedules.html["Horarios de facturación"]

