---
sidebar: sidebar 
permalink: concepts/qos.html 
keywords: PSL and QoS, service level quality of service 
summary: Calidad de servicio en Keystone 
---
= Calidad de servicio en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La calidad de servicio (QoS) de almacenamiento es una tecnología vital que garantiza que las aplicaciones obtienen un rendimiento constante y predecible. Sin calidad de servicio, ciertas cargas de trabajo, como las para el arranque de varios sistemas, pueden consumir la mayoría o todos los recursos durante un período y afectar a las otras cargas de trabajo. Para obtener más información sobre QoS, consulte https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html["Garantice el rendimiento con información general de calidad de servicio"^].



== Calidad de servicio adaptativa

Los servicios de Keystone utilizan la calidad de servicio adaptativa (AQoS) para mantener de forma dinámica la relación de IOPS/TiB en función del tamaño del volumen. Para obtener información acerca de las políticas AQoS, consulte https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos["Acerca de la calidad de servicio adaptativa"^].

Keystone le proporciona políticas de AQoS que puede configurar una vez que su clúster se encuentre en producción. Debe asegurarse de que todos los volúmenes estén asociados con las políticas de AQoS correctas que ya se han creado y están disponibles en el sistema.

Un volumen de ONTAP no es compatible si no se aplica una política AQoS. Un volumen sin una política de calidad de servicio es el último de la lista de prioridades del sistema para que proporcione las operaciones de entrada y salida disponibles. Sin embargo, si hay alguna operación de entrada y salida disponible, el volumen podría consumir todos los iOS disponibles.


NOTE: Si no has aplicado políticas de calidad de servicio (AQoS) a tus volúmenes, dichos volúmenes se medirán y cobrarán en el nivel de servicio más alto según tu suscripción. Esto puede resultar en cargos de ráfaga no intencionados.



== Configuración de calidad de servicio adaptativa

La configuración de calidad de servicio adaptativa (AQoS) varía según los niveles de servicio.

|===


| *Nombre de la política* | *Extremo* | *Premium* | *Rendimiento* | *Estándar* | *Valor* 


| *IOPS esperado* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Asignación de IOPS esperada* 5+| Espacio asignado 


| *Peak IOPS* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Asignación de IOPS pico* 5+| El espacio utilizado 


| *Tamaño de bloque* 5+| 32K 
|===


== Configuración del grupo de políticas de calidad de servicio adaptativo

Puede configurar las políticas de calidad de servicio adaptativas (AQoS) para escalar automáticamente un techo de rendimiento o un tamaño piso a uno del volumen. No todos los niveles de servicio de Keystone están alineados con las políticas de calidad de servicio de ONTAP predeterminadas. Puede crear políticas de calidad de servicio personalizadas para ellas. Para configurar una directiva, debe tener en cuenta lo siguiente:

* *Nombre del grupo de políticas*: Nombre del grupo de políticas AQoS. Por ejemplo: `Keystone_extreme`.
* *VServer*: El nombre del VServer o del VM de almacenamiento (máquina virtual de almacenamiento).
* *IOPS esperadas*: El número mínimo de IOPS, por TiB asignado por volumen, que el sistema intenta proporcionar cuando hay suficientes IOPS del sistema disponibles.
* *Peak IOPS*: El número máximo de IOPS, por TiB usado por volumen, que el sistema permite que el volumen alcance antes de regular la IOPS mediante la inyección de latencia.
* *Asignación de IOPS esperada*: Este parámetro controla si la IOPS esperada disponible para el volumen se basa en el tamaño asignado o utilizado del volumen. En Keystone, se basa en el espacio asignado.
* *Asignación de IOPS pico*: Este parámetro controla si el valor máximo de IOPS disponible para el volumen se basa en el tamaño asignado o utilizado del volumen. En Keystone, se basa en el espacio usado.
* *IOPS mínimo absoluto*: El número más bajo de IOPS esperadas que se aplicará a un volumen si el tamaño del volumen es muy pequeño y, de lo contrario, resultaría en un número inaceptable de IOPS. De forma predeterminada, este valor es 1,000 para `Extreme`, 500 para `Premium`, y 250 para `Performance`, y 75 para `Standard` y.. `Value` niveles de servicio.
+

NOTE: Esto no es una densidad de IOPS (por ejemplo, 75 IOPS/TIB), sino un número mínimo absoluto de IOPS.



Para obtener más información sobre la densidad de I/o, consulte link:../concepts/metrics.html["Métricas y definiciones utilizadas en los servicios de Keystone"]. Para obtener más información acerca de los grupos de políticas AQoS, consulte https://docs.netapp.com/us-en/ontap/performance-admin/adaptive-qos-policy-groups-task.html["Utilice grupos de políticas de calidad de servicio adaptativos"^].



== Ajustes de las políticas de calidad de servicio adaptativas

La configuración de las políticas de QoS adaptativo (AQoS) para cada nivel de servicio se describe en las secciones siguientes. Los tamaños mínimos y máximos de volumen para cada nivel de servicio proporcionado aquí permiten obtener valores óptimos de IOPS y latencia para un volumen. Crear demasiados volúmenes fuera de estas directrices puede afectar de forma negativa al rendimiento de estos volúmenes.



=== Configuración del nivel de servicio extremo

Configuraciones y comandos para el nivel de servicio extremo:

* Comando de ejemplo:


....
qos adaptive-policy-group create -policy-group <Keystone_extreme> -vserver <SVM_name> -expected-iops 6144 -peak-iops 12288 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 1000
....
* Tamaño mínimo de volumen: 100 GIB, 0,1 TIB
* Tamaño máximo de volumen: 10 TIB




=== Configuración del nivel de servicio Premium

Configuración y comandos para el nivel de servicio Premium:

* Comando de ejemplo:


....
qos adaptive-policy-group create -policy-group <Keystone_premium> -vserver <SVM_name> -expected-iops 2048 -peak-iops 4096 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 500
....
* Tamaño mínimo de volumen: 500 GIB, 0,5 TIB
* Tamaño máximo de volumen: 50 TIB




=== Configuración del nivel de servicio de rendimiento

Ajustes y comandos para el nivel de servicio rendimiento:

* Comando de ejemplo:


....
qos adaptive-policy-group create -policy-group <Keystone_performance> -vserver <SVM_name> -expected-iops 1024 -peak-iops 2048 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 250
....
* Tamaño mínimo de volumen: 500 GIB, 0,5 TIB
* Tamaño máximo de volumen: 80 TIB




=== Configuración del nivel de servicio estándar

Configuración y comandos para el nivel de servicio estándar:

* Comando de ejemplo:


....
qos adaptive-policy-group create -policy-group <Keystone_standard> -vserver <SVM_name> -expected-iops 256 -peak-iops 512 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Tamaño mínimo de volumen: 1 TIB
* Tamaño máximo de volumen: 100 TIB




=== Configuración del nivel de servicio de valor

Configuración y comandos para el nivel de servicio de valor:

* Comando de ejemplo:


....
qos adaptive-policy-group create -policy-group <Keystone_value> -vserver <SVM_name> -expected-iops 64 -peak-iops 128 -expected-iops-allocation allocated-space -peak-iops-allocation used-space -block-size 32K -absolute-min-iops 75
....
* Tamaño mínimo de volumen: 1 TIB
* Tamaño máximo de volumen: 100 TIB




== Cálculo del tamaño de bloque

Tenga en cuenta estos puntos antes de calcular el tamaño de bloque utilizando estos ajustes:

* IOPS/TIB = Mbps/TIB dividido por (tamaño de bloque * 1024)
* El tamaño del bloque es en KB/I/O.
* TIB = 1024 GIB; GIB = 1024 MiB; MIB = 1024 KiB; KiB = 1024 bytes; según base 2
* TB = 1000 GB; GB = 1000 MB; MB = 1000 KB; KB = 1000 bytes; según base 10


.Cálculo del tamaño del bloque de muestra
Para calcular el rendimiento de un nivel de servicio, por ejemplo `Extreme` nivel de servicio:

* Máximo de IOPS: 12,288
* Tamaño de bloque por I/o: 32 KB
* Rendimiento máximo = (12288 * 32 * 1024) / (1024*1024) = 384 MBps/TIB


Si un volumen tiene 700 GIB de datos lógicos usados, el rendimiento disponible será:

`Maximum throughput = 384 * 0.7 = 268.8MBps`
