---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: Keystone STaaS para la versión 3 ofrece capacidad de almacenamiento en niveles de servicio predefinidos. Cada volumen que gestiona Keystone está asociado con un nivel de servicio. 
---
= Niveles de servicio de rendimiento en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS para la versión 3 (v3) ofrece capacidad de almacenamiento de datos en niveles de servicio de rendimiento predefinidos. Cada volumen administrado por los servicios de Keystone está asociado a un nivel de servicio de rendimiento.

Una suscripción puede tener varios planes de tarifas, y cada uno corresponde a un nivel de servicio de rendimiento. Cada plan de tarifas tiene una capacidad comprometida por nivel de servicio de rendimiento.

Un nivel de servicio de rendimiento puede tener varias instancias, cada una de las cuales representa una matriz de almacenamiento independiente asignada a dicho nivel en el entorno del cliente. Cada nivel de servicio de rendimiento se define por las operaciones de entrada/salida por segundo (IOPS), el rendimiento (GBps) y la latencia (ms); estas métricas se miden y aplican por instancia de nivel de servicio de rendimiento.

Usted selecciona los niveles de servicio de rendimiento según su entorno de almacenamiento y sus necesidades de almacenamiento y consumo. Los niveles de servicio de rendimiento básico están disponibles para usted de forma predeterminada. También están disponibles niveles de servicio de rendimiento específicos, si ha optado por servicios complementarios.


TIP: Está disponible una descripción detallada del servicio para los niveles de rendimiento del servicio NetApp Keystone STaaS  https://www.netapp.com/services/keystone/terms-and-conditions/["aquí"^] .

Los niveles de servicio de rendimiento base para los tipos de almacenamiento admitidos, unificados, optimizados por bloques, de objetos y de nube se describen en las siguientes secciones:



== Niveles de servicio de rendimiento para almacenamiento unificado

*Protocolos compatibles*: FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3

|===


| *Nivel de servicio de rendimiento* (todas las especificaciones por instancia de nivel de servicio de rendimiento) | *Extremo* | *Premium* | *Estándar* | *Valor* 


| *Tipos de carga de trabajo de ejemplo* | IA/ML, HPC, base de datos InMem | Análisis, EDA, OLTP | OLAP, IoT, Contenedores | Copia de seguridad, archivo 


| *IOPS máximos*^1^ | 1M | 550K | 500K | NA 


| *Máximo de GBps* | 40 | 20 | 20 | NA 


| *Objetivo 90^TH^ latencia percentil* | <=1 ms | <=1 ms | <=4 ms | >4 ms 


| *Capacidad mínima comprometida* | 50 TiB | 50 TiB | 100 TiB | 100 TiB 


| *Aumento incremental de la capacidad comprometida* 4+| 25TiB 


| *Tipo de capacidad comprometida y medida* 4+| Lógico o físico 
|===


== Niveles de servicio de rendimiento para almacenamiento optimizado por bloques

*Protocolos compatibles*: NVMe/TCP, NVMe/FC, FC, iSCSI

|===


| *Nivel de servicio de rendimiento* (todas las especificaciones por instancia de nivel de servicio de rendimiento) | *Extremo* | *Premium* 


| *Tipos de carga de trabajo de ejemplo* 2+| SAP HANA, Oracle, MS SQL Server, EPIC 


| *IOPS máximos*^1^ | 850K | 450K 


| *Máximo de GBps* | 65 | 25 


| *Objetivo 90^TH^ latencia percentil* | <=1 ms | <=1 ms 


| *Capacidad mínima comprometida* | 50 TiB | 50 TiB 


| *Aumento incremental de la capacidad comprometida* 2+| 25TiB 


| *Tipo de capacidad comprometida y medida* 2+| Lógico o físico 
|===

NOTE: ^1^Objetivos mutuamente excluyentes. El rendimiento real puede variar según diversos factores, como la versión del sistema operativo, el hardware, el tipo de carga de trabajo y el número de operaciones simultáneas.



=== Más información sobre los niveles de servicio de rendimiento para el almacenamiento unificado y optimizado por bloques

Las métricas de nivel de servicio de rendimiento base dependen de las siguientes condiciones:

* Los niveles de servicio de rendimiento admiten ONTAP 9.8 y versiones posteriores.
* Para un almacenamiento unificado,
+
** *IOPS*: Para ONTAP 9.16.1 con NFS, cada instancia de nivel de rendimiento admite acceso aleatorio con una relación de lectura del 70 % y escritura del 30 %, un tamaño de bloque de 8 KB y una latencia de 1 ms (4 ms para estándar).
** *Rendimiento*: para ONTAP 9.16.1 con NFS, cada instancia de nivel de rendimiento admite acceso secuencial con 100 % de lectura y un tamaño de bloque de 32 KB.


* Para un almacenamiento optimizado por bloques,
+
** *IOPS*: Para ONTAP 9.16.1 con FCP, cada instancia de nivel de rendimiento admite acceso aleatorio con una relación de lectura del 70 % y escritura del 30 %, un tamaño de bloque de 8 KB y una latencia de 1 ms.
** *Rendimiento*: para ONTAP 9.16.1 con FCP, cada instancia de nivel de rendimiento admite acceso secuencial con 100 % de lectura y un tamaño de bloque de 64 KB.


* La latencia no incluye lo siguiente:
+
** latencia de aplicaciones o host
** latencia de red del cliente hacia o desde los puertos de la controladora
** Costes generales asociados a la transferencia de datos al almacén de objetos, en caso de FabricPool


* Los valores de latencia no son aplicables a las operaciones de escritura de MetroCluster. Estas operaciones de escritura dependen de la distancia de los sistemas remotos.
* _Expected IOPS_ está dirigido a FabricPool solo si la política de organización en niveles se establece en «ninguno» y no hay bloques en el cloud. _Expected IOPS_ se dirige a volúmenes que no están en una relación de SnapMirror síncrona.




== Niveles de servicio de rendimiento para el almacenamiento de objetos

*Protocolo admitido*: S3

|===


| *Nivel de servicio de rendimiento* | *Estándar* | *Valor* 


| *Capacidad mínima comprometida por pedido* | 200 TiB | 500 TiB 


| *Aumento incremental de la capacidad comprometida* | 25 TiB | 100 TiB 


| *Tipo de capacidad comprometida y medida* 2+| Físico 
|===


== Almacenamiento en cloud

*Protocolos compatibles*: NFS, CIFS, iSCSI y S3 (solo AWS y Azure)

|===


| *Nivel de servicio de rendimiento* | Cloud Volumes ONTAP 


| *Capacidad mínima comprometida por pedido* | 4 TiB 


| *Aumento incremental de la capacidad comprometida* | 1 TiB 


| *Tipo de capacidad comprometida y medida* | Lógico 
|===
[NOTE]
====
* Los servicios nativos del cloud, como la computación, el almacenamiento o las redes, los proveedores de cloud facturan.
* Estos servicios dependen de las características del almacenamiento en cloud y del equipo.


====
*Información relacionada*

* link:../concepts/supported-storage-capacity.html["Capacidades de almacenamiento admitidas"]
* link:..//concepts/metrics.html["Métricas y definiciones utilizadas en los servicios de Keystone"]
* link:../concepts/pricing.html["Precios Keystone"]

