---
sidebar: sidebar 
permalink: concepts/service-levels.html 
keywords: service levels, service level, rate plan or service level 
summary: STaaS de Keystone ofrece capacidad de almacenamiento a niveles de servicio predefinidos. Cada volumen que gestiona Keystone está asociado con un nivel de servicio. 
---
= Niveles de servicio de rendimiento en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
STaaS de Keystone ofrece capacidad de almacenamiento de datos a niveles de servicio de rendimiento predefinidos. Cada volumen administrado por los servicios de Keystone está asociado a un nivel de servicio de rendimiento.

Una suscripción puede tener varios planes de tarifas, y cada uno corresponde a un nivel de servicio de rendimiento. Cada plan de tarifas tiene una capacidad comprometida por nivel de servicio de rendimiento.

Cada nivel de servicio de rendimiento se define por su densidad de E/S, es decir IOPS/TiB/volumen. Esta es la proporción de rendimiento (operaciones de entrada/salida por segundo [IOPS]) y la capacidad de almacenamiento utilizada (TiB), que es IOPS/TiB con una latencia media por volumen.

Puede seleccionar los niveles de servicio de rendimiento según su entorno de almacenamiento y sus necesidades de almacenamiento y consumo. Los niveles de servicio de rendimiento básicos están disponibles por defecto. Si ha optado por servicios complementarios, también dispone de niveles de servicio de rendimiento específicos. Por ejemplo, para el servicio complementario de protección de datos avanzada, el nivel de servicio de rendimiento _Advanced Data-Protect_ se asigna a su suscripción.


TIP: Está disponible una descripción detallada del servicio para los niveles de rendimiento del servicio NetApp Keystone STaaS  https://www.netapp.com/services/keystone/terms-and-conditions/["aquí"^] .

Los niveles de servicio de rendimiento básico para los tipos de almacenamiento admitidos, archivos, bloques, objetos y servicios en la nube se describen en las siguientes secciones:



== Niveles de servicio de rendimiento para almacenamiento de archivos y bloques

*Protocolos compatibles*: NFS, CIFS, iSCSI y FC

|===


| *Nivel de servicio de rendimiento* | *Extremo* | *Premium* | *Rendimiento* | *Estándar* | *Valor* 


| *Tipos de carga de trabajo de ejemplo* | Análisis, bases de datos, aplicaciones críticas para la misión | VDI, VSI, desarrollo de software | OLTP, OLAP, contenedores, desarrollo de software | Archivos compartidos, servidores web | Backup 


| *IOPS máximo/TIBs lógicos almacenados por volumen* | 12,288 | 4,096 | 2,048 | 512 | 128 


| *Máximo IOPS/TIBs lógicos asignados por volumen* | 6,144 | 2,048 | 1,024 | 256 | 64 


| *Máximo Mbps/TIBs lógicos almacenados por volumen a 32K B/S* | 384 | 128 | 64 | 16 | 4 


| *Objetivo 90^TH^ latencia percentil* | <1 ms | <2 ms | <4 ms | <4 ms | <17 ms 


| *Tamaño del bloque* 5+| 32K 


| *Tipo de capacidad comprometida y medida* 5+| Lógico 
|===


=== Más información sobre los niveles de servicio de rendimiento para el almacenamiento de archivos y bloques

Las métricas de nivel de servicio de rendimiento base dependen de las siguientes condiciones:

* Los niveles de servicio de rendimiento para el almacenamiento de archivos y bloques admiten ONTAP 9.7 y versiones posteriores.
* Los valores de IOPS/TiB/volumen, MBps/TiB/volumen y latencia para los niveles de servicio de rendimiento se basan en la cantidad de datos almacenados en el volumen, un tamaño de bloque de 32 KB y una combinación aleatoria de 70 % de operaciones de E/S de lectura y 30 % de escritura.
* Las operaciones de IOPS/TiB/volumen reales y MBps/TiB/volumen pueden variar en función del tamaño de bloque real o asumido, la concurrencia de la carga de trabajo del sistema o las operaciones de entrada y salida.
* La latencia no incluye lo siguiente:
+
** latencia de aplicaciones o host
** latencia de red del cliente hacia o desde los puertos de la controladora
** Costes generales asociados a la transferencia de datos al almacén de objetos, en caso de FabricPool
** Latencia aplicada automáticamente por QoS para mantener la E/S dentro de los máximos del nivel de servicio de rendimiento


* Los valores de latencia no son aplicables a las operaciones de escritura de MetroCluster. Estas operaciones de escritura dependen de la distancia de los sistemas remotos.
* Si uno o más volúmenes de un sistema de almacenamiento no tienen una política AQoS asignada, entonces estos volúmenes se consideran como volúmenes no compatibles y no se aplican niveles de servicio de rendimiento objetivo para esos sistemas.
* _Expected IOPS_ está dirigido a FabricPool solo si la política de organización en niveles se establece en «ninguno» y no hay bloques en el cloud. _Expected IOPS_ se dirige a volúmenes que no están en una relación de SnapMirror síncrona.
* Las operaciones de I/O de carga de trabajo deben equilibrarse en todas las controladoras puestas en marcha, según lo determine el orden de Keystone.




== Almacenamiento de objetos

*Protocolo admitido*: S3

|===


| *Nivel de servicio de rendimiento* | Objeto 


| *Tipo de carga de trabajo* | Almacén de medios, archivado 


| *IOPS máximo/TIB lógico almacenados por volumen* | N.A. 


| *Máximo Mbps/TIB lógico almacenado por volumen* | N.A. 


| *Latencia media* | N.A. 


| *Tipo de capacidad comprometida y medida* | Físico 
|===

NOTE: La latencia no incluye sobrecargas asociadas con la transferencia de datos al almacén de objetos en el caso de almacenamiento de FabricPool.



== Almacenamiento en cloud

*Protocolo compatible*: NFS, CIFS, iSCSI y S3 (solo AWS y Azure)

|===


| *Nivel de servicio de rendimiento* | Cloud Volumes ONTAP 


| *Tipo de carga de trabajo* | Recuperación ante desastres, desarrollo y pruebas de software, aplicaciones empresariales 


| *IOPS máximo/TIB lógico almacenados por volumen* | N.A. 


| *Máximo Mbps/TIB lógico almacenado por volumen* | N.A. 


| *Latencia media* | N.A. 
|===
[NOTE]
====
* Los servicios nativos del cloud, como la computación, el almacenamiento o las redes, los proveedores de cloud facturan.
* Estos servicios dependen de las características del almacenamiento en cloud y del equipo.


====
*Información relacionada*

* link:../concepts/supported-storage-capacity.html["Capacidades de almacenamiento admitidas"]
* link:..//concepts/metrics.html["Métricas y definiciones utilizadas en los servicios de Keystone"]
* link:../concepts/qos.html["Calidad de servicio en Keystone"]
* link:../concepts/pricing.html["Precios Keystone"]

