---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Obtén más información sobre los tipos de capacidades de almacenamiento que admite el servicio STaaS de NetApp Keystone. 
---
= Capacidades de almacenamiento compatibles con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El servicio STaaS de NetApp Keystone es compatible con varios tipos de capacidades de almacenamiento. Entender estos diferentes términos de capacidad puede ayudar cuando usa Keystone.



== Capacidad lógica

Estos son los datos que pone un cliente en la infraestructura de Keystone. Todas las capacidades de Keystone se refieren a una capacidad lógica. Por ejemplo, si se almacena un archivo de 1 TIB en la infraestructura de Keystone, debe adquirirse un mínimo de 1 TIB de capacidad.



== Capacidad comprometida

La capacidad lógica mínima facturada cada mes durante la suscripción:

* La capacidad se compromete con cada nivel de servicio.
* Durante el período de vigencia se puede añadir la capacidad comprometida y los niveles de servicio adicionales.




=== Cambios en la capacidad comprometida

Durante la duración de una suscripción, puede cambiar las capacidades comprometidas. Sin embargo, existen algunas condiciones previas:

* La capacidad comprometida puede disminuirse en función de ciertas condiciones. Para obtener más información, consulte link:../concepts/capacity-requirements.html["Reducción de capacidad"].
* La capacidad comprometida no puede aumentarse 90 días antes del vencimiento de su suscripción, a menos que la suscripción se vaya a renovar por un período adicional de 12 meses.
* Puede solicitar cambios en la capacidad confirmada a través de la interfaz de BlueXP o a través de Keystone Success Manager (KSM). Para obtener información sobre la solicitud de cambios, consulte link:../concepts/gssc.html["Soporte de NetApp Keystone"].




== La capacidad consumida

La capacidad consumida hace referencia a la capacidad (en TIB de almacenamiento) que se está consumiendo actualmente en el servicio. Es la suma de:

* La capacidad lógica utilizada para almacenar todas las instancias y tipos de datos de usuario (como copias, copias reflejadas y versiones).
* La capacidad lógica utilizada para almacenar volúmenes de clonado que son más del 10 % del tamaño del volumen original.
* La capacidad física utilizada para almacenar los datos diferenciales de las copias Snapshot.
* La capacidad física asignada.




== Capacidad de ráfaga

El servicio Keystone le permite usar capacidad adicional sobre la capacidad comprometida para un nivel de servicio. Este es el uso de la capacidad de ráfaga. Tenga en cuenta estos puntos:

* La capacidad de ráfaga se acuerda en el acuerdo de Keystone. Normalmente se configura hasta un 20% por encima de la capacidad comprometida y se carga a la misma tasa que la capacidad comprometida.
* La capacidad de ráfaga se puede consumir sobre una base flexible y se cobra diariamente por la media consumida.




== Capacidad facturada

Factura mensual = (capacidad comprometida [TIB] * tasa comprometida [$/TIB]) + (capacidad de ráfaga aprovisionada media diaria [TIB] * tasa de ráfaga [$/TIB]). La factura mensual contiene un cargo mínimo basado en la capacidad comprometida.

La factura mensual varía más allá del cargo mínimo en función del consumo medio de capacidad de ráfaga diaria.
