---
sidebar: sidebar 
permalink: concepts/support-services.html 
keywords: Keystone support, service request, support ticket 
summary: Usa el sitio de soporte de NetApp para crear un caso de soporte o encontrar información de contacto para tus suscripciones de Keystone. 
---
= Obtén ayuda con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp proporciona a los clientes de Keystone servicios operativos. Los clientes reciben un Keystone Success Manager (KSM) dedicado, opciones de contacto de soporte técnico directo y supervisión proactiva a través de la solución ITOM.



== NetApp servicios de soporte

NetApp ofrece servicios operativos de forma remota a los clientes de Keystone. Estos servicios abarcan una gama de actividades de gestión del almacenamiento, incluyendo la gestión de activos y configuraciones, la gestión de capacidad y rendimiento, la gestión de cambios, la gestión de eventos e incidentes, la atención de solicitudes de servicio y la elaboración de informes.

.Keystone Success Manager
Tu KSM trabaja estrechamente contigo en tus servicios Keystone y te proporciona informes semanales o mensuales de facturación y operativos. Las responsabilidades específicas se definen en tu acuerdo NetApp Keystone.



== Contacta con soporte técnico

Si tienes algún problema con tu suscripción a Keystone, inicia sesión en link:https://support.netapp.com["Sitio de soporte de NetApp"^] con tus credenciales de NSS para crear un caso de soporte técnico.

Si no tienes un inicio de sesión NSS, link:https://mysupport.netapp.com/site/user/registration["registra tu cuenta"^] usando el número de serie (SN) de uno de los nodos de tu suscripción.

Para obtener instrucciones paso a paso con capturas de pantalla, consulta link:https://kb.netapp.com/nss/Support_Site/How_to_open_a_technical_support_case["Cómo abrir un caso de soporte técnico"^].

Si prefieres hablar directamente con un representante de soporte, llama a uno de los siguientes números:

* EE. UU. / Canadá: 888 463 8277
* Europa: 00 800 44 638277
* India: 000 800 100 8948
* Más cifras globales: link:https://www.netapp.com/company/contact-us/support/["https://www.netapp.com/company/contact-us/support/"^]




== Supervisión de soporte

NetApp utiliza la solución de supervisión ITOM para supervisar de forma proactiva el estado de tus productos y servicios suscritos y conectarse al entorno NetApp Keystone para la resolución de problemas.



== Recursos adicionales

Para obtener más información sobre los servicios de Keystone, consulte:

* link:https://www.netapp.com/us/solutions/keystone/index.aspx["NetApp Keystone"^]
* link:https://docs.netapp.com["NetApp Documentación del producto"^]


*Información relacionada*

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_Identify_Serial_Number_of_ONTAP_Platform["Cómo identificar el número de serie de la plataforma ONTAP"^]
* link:https://kb.netapp.com/hybrid/StorageGRID/Maintenance/Which_serial_number_to_use_when_creating_StorageGRID_technical_support_case["Qué número de serie usar al crear un caso de soporte técnico de StorageGRID"^]

