---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Servicios Keystone STaaS 
---
= Almacenamiento compatible en servicios de Keystone STaaS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los servicios de Keystone STaaS admiten almacenamiento de archivos y bloques de ONTAP, almacenamiento de objetos de la plataforma StorageGRID y funcionalidades de gestión de datos de Cloud Volumes ONTAP.

Keystone STaaS proporciona servicios estándar y opcionales para su almacenamiento.

*Servicios estándar Keystone STaaS*: Los servicios estándar están incluidos dentro de la suscripción básica y no se cobran por separado.

*Servicios complementarios de Keystone STaaS*: Estos son servicios opcionales que se pueden cargar y que proporcionan utilidades y beneficios adicionales además de los servicios de suscripción estándar de Keystone STaaS.

Los servicios de Keystone STaaS pueden coexistir entre sí. Por ejemplo, una suscripción al almacenamiento en cloud puede coexistir con las suscripciones a almacenamiento de archivos, bloques y objetos. Un servicio cloud puede incluirse en cualquier punto durante el plazo de servicio de una suscripción a almacenamiento existente. Sin embargo, si no tiene pensado renovar una suscripción existente de archivo, bloque y objeto, no podrá agregar una suscripción de almacenamiento en la nube durante los últimos 90 días de la suscripción.



== Servicios para almacenamiento de archivos, bloques y objetos

Los servicios de Keystone STaaS para almacenamiento de archivos y bloques de ONTAP y almacenamiento de objetos de StorageGRID admiten varias funciones y protocolos, y se describen en la siguiente tabla:

|===
| Reducida | Plataforma | Protocolos | Funciones admitidas 


 a| 
Almacenamiento de archivos
 a| 
ONTAP
 a| 
NFS y CIFS
 a| 
Funciones de ONTAP compatibles:

* FlexVol
* FlexGroup
* Copias Snapshot
* SnapMirror (asíncrono)
* SnapVault
* Empresa SnapLock
* FabricPool/organización en niveles en el cloud
* SnapRestore
* FlexClone
* SnapCenter (la licencia está incluida, pero no forma parte de los servicios de Keystone y la gestión no está garantizada).
* Protección autónoma contra ransomware^1^




 a| 
Almacenamiento en bloques
 a| 
ONTAP
 a| 
FC e iSCSI
 a| 
Funciones de ONTAP compatibles:

* FlexVol
* FlexGroup
* Copias Snapshot
* SnapMirror (asíncrono)
* SnapVault
* Empresa SnapLock
* FabricPool/organización en niveles en el cloud
* SnapRestore
* FlexClone
* SnapCenter (la licencia está incluida, pero no forma parte de los servicios de Keystone y la gestión no está garantizada).




 a| 
Almacenamiento de objetos
 a| 
StorageGRID
 a| 
S3
 a| 
Admite múltiples directivas de gestión del ciclo de vida de la información (ILM) en varios sitios^2^

|===

NOTE: ^1^ Para obtener más información sobre la protección frente a ransomware en ONTAP, consulte https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Protección autónoma de ransomware"^].
^2^ Cada sitio requiere una suscripción independiente.



== Servicios para almacenamiento en cloud

Keystone STaaS proporciona servicios de almacenamiento en cloud. Keystone STaaS admite funcionalidades de gestión de datos Cloud Volumes ONTAP en Amazon Web Services (AWS), Microsoft Azure y Google Cloud Platform.


NOTE: NetApp no suministra los servicios informáticos, de almacenamiento y de red basados en a hiperescala necesarios para Cloud Volumes ONTAP como parte de las suscripciones de Keystone STaaS; estas suscripciones deben obtenerse directamente de los proveedores de servicios cloud a hiperescala.
