---
sidebar: sidebar 
permalink: concepts/supported-storage-capacity.html 
keywords: storage capacity, capacity definition, keystone STaaS storage capacity, 
summary: Conozca los tipos de capacidades de almacenamiento compatibles con el servicio NetApp Keystone STaaS para la versión 3. 
---
= Capacidades de almacenamiento compatibles con Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
El servicio NetApp Keystone STaaS admite varios tipos de capacidades de almacenamiento. Comprender estos diferentes términos de capacidad puede resultar útil al utilizar Keystone.



== Capacidad lógica

Esta es la cantidad de capacidad de almacenamiento necesaria para almacenar datos del usuario antes de que se apliquen las eficiencias de datos proporcionadas por la matriz de almacenamiento.



== Capacidad comprometida

La capacidad lógica mínima facturada cada mes durante la suscripción:

* La capacidad se compromete con cada nivel de servicio.
* Se pueden agregar capacidad comprometida y niveles de servicio de rendimiento adicionales durante el plazo.




=== Cambios en la capacidad comprometida

Durante la duración de una suscripción, puede cambiar las capacidades comprometidas. Sin embargo, existen algunas condiciones previas:

* La capacidad comprometida puede disminuirse en función de ciertas condiciones. Para obtener más información, consulte link:../concepts/capacity-requirements.html["Reducción de capacidad"].
* La capacidad comprometida no puede aumentarse 90 días antes del vencimiento de su suscripción, a menos que la suscripción se vaya a renovar por un período adicional de 12 meses.
* Puede solicitar cambios en la capacidad comprometida a través de la interfaz de BlueXP o desde su Keystone Success Manager (KSM). Para obtener información sobre la solicitud de cambios, consulte link:../concepts/gssc.html["Soporte de NetApp Keystone"].




== La capacidad consumida

La capacidad consumida hace referencia a la capacidad (en TIB de almacenamiento) que se está consumiendo actualmente en el servicio. Se calcula de forma diferente según el tipo de almacenamiento:

* *Almacenamiento unificado u optimizado por bloques*: la capacidad consumida se calcula en función del tipo de capacidad (lógica o física) seleccionada durante el proceso de pedido.  El cálculo se realiza por instancia de nivel de servicio de rendimiento.
+
.. *Capacidad lógica*: Es la suma de:
+
*** Capacidad lógica medida, antes de las eficiencias de los datos de la matriz de almacenamiento, para almacenar todas las instancias y tipos de datos de clientes, como copias, copias reflejadas, versiones y clones.
*** Capacidad física utilizada para almacenar metadatos y datos diferenciales de instantáneas y ciertos clones.
*** Cualquier capacidad física con gran capacidad de aprovisionamiento.


.. *Capacidad física*: Es la suma de:
+
*** Capacidad física medida, después de las eficiencias de los datos de la matriz de almacenamiento, para almacenar todas las instancias y tipos de datos del cliente, como copias, copias reflejadas, versiones, clones.
*** Capacidad física utilizada para almacenar metadatos y datos diferenciales de instantáneas.
*** Cualquier capacidad física con gran capacidad de aprovisionamiento.




* Almacenamiento de objetos: La capacidad consumida se calcula como la cantidad de capacidad física medida utilizada para almacenar todas las instancias y tipos de datos de clientes en todos los nodos. Este cálculo se basa en las políticas de gestión del ciclo de vida de la información (ILM) configuradas.
* *Cloud Volumes ONTAP*: la capacidad consumida se calcula como la cantidad de capacidad aprovisionada medida de todos los volúmenes de Cloud Volumes ONTAP.




== Capacidad de ráfaga

El servicio NetApp Keystone STaaS le permite usar capacidad adicional a la capacidad comprometida para un nivel de servicio de alto rendimiento. Esto se conoce como uso de capacidad en ráfagas.

Tenga en cuenta estos puntos:

* La capacidad de ráfaga se acuerda en el acuerdo de Keystone. Generalmente se configura hasta un 20 % por encima de la capacidad comprometida, por instancia de nivel de servicio de rendimiento, con opciones adicionales disponibles para seleccionar límites de capacidad de ráfaga del 40 % o 60 % de la capacidad comprometida.
* El consumo de capacidad máxima se factura a la misma tarifa que la capacidad comprometida correspondiente al nivel de servicio de rendimiento seleccionado.
* Los servicios STaaS de Keystone brindan un período de exención de ráfaga de 60 días a partir de la fecha de inicio.




== Capacidad facturada

Factura mensual = (capacidad comprometida [TIB] * tasa comprometida [$/TIB]) + (capacidad de ráfaga aprovisionada media diaria [TIB] * tasa de ráfaga [$/TIB]). La factura mensual contiene un cargo mínimo basado en la capacidad comprometida.

La factura mensual varía más allá del cargo mínimo en función del consumo medio de capacidad de ráfaga diaria.
