---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Los servicios STaaS de Keystone son compatibles con ONTAP y StorageGRID. 
---
= Almacenamiento compatible en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los servicios Keystone STaaS para la versión 3 (v3) admiten el almacenamiento unificado, optimizado por bloques y de objetos de NetApp y Cloud Volumes ONTAP.

Cada tipo de almacenamiento incluye:

* *Almacenamiento unificado*: incluye almacenamiento de archivos, bloques y objetos S3, disponible en sistemas NetApp ONTAP AFF y FAS.
* *Almacenamiento optimizado en bloques*: incluye almacenamiento en bloques disponible en los sistemas NetApp ONTAP ASA.
* *Almacenamiento de objetos*: incluye almacenamiento de objetos disponible en sistemas NetApp StorageGRID.


Keystone STaaS proporciona servicios estándar y opcionales para su almacenamiento.

*Servicios estándar Keystone STaaS*: Los servicios estándar están incluidos dentro de la suscripción básica y no se cobran por separado.

*Servicios complementarios de Keystone STaaS*: Estos son servicios opcionales que se pueden cargar y que proporcionan utilidades y beneficios adicionales además de los servicios de suscripción estándar de Keystone STaaS.

Los servicios de Keystone STaaS se pueden usar simultáneamente. Por ejemplo, una suscripción de almacenamiento en la nube puede tener la misma duración que las suscripciones unificadas, optimizadas por bloques y de almacenamiento de objetos. Un servicio cloud puede incluirse en cualquier punto durante el plazo de servicio de una suscripción a almacenamiento existente. Sin embargo, si no planea renovar una suscripción unificada, optimizada por bloques o de almacenamiento de objetos existente, no podrá añadir una suscripción de almacenamiento en la nube durante los últimos 90 días de la suscripción.



== Servicios para almacenamiento unificado, optimizado por bloques y de objetos

Los servicios Keystone STaaS para almacenamiento unificado, optimizado por bloques y de objetos admiten múltiples funciones y protocolos, y se describen en la siguiente tabla:

|===
| Reducida | Plataforma | Protocolos | Funciones admitidas 


 a| 
Almacenamiento unificado
 a| 
ONTAP
 a| 
NFS y CIFS
 a| 
Admite todas las funciones de ONTAP One



 a| 
Almacenamiento optimizado por bloques
 a| 
ONTAP
 a| 
FC e iSCSI
 a| 
Admite todas las funciones de ONTAP One



 a| 
Almacenamiento de objetos
 a| 
StorageGRID
 a| 
S3
 a| 
Admite todas las funciones de ONTAP One

|===
Para obtener más información sobre ONTAP One, consulte link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Información general de las licencias de ONTAP"^] y link:https://www.netapp.com/blog/ontap-one/["ONTAP One: Todo el poder de ONTAP, ahora todo en uno"^] .



== Servicios para almacenamiento en cloud

Keystone STaaS proporciona servicios de almacenamiento en cloud. Keystone STaaS admite funcionalidades de gestión de datos Cloud Volumes ONTAP en Amazon Web Services (AWS), Microsoft Azure y Google Cloud Platform.


NOTE: NetApp no suministra los servicios informáticos, de almacenamiento y de red basados en a hiperescala necesarios para Cloud Volumes ONTAP como parte de las suscripciones de Keystone STaaS; estas suscripciones deben obtenerse directamente de los proveedores de servicios cloud a hiperescala.
