---
sidebar: sidebar 
permalink: concepts/supported-storage-services.html 
keywords: storage, service, service definition, keystone STaaS services, 
summary: Los servicios STaaS de Keystone son compatibles con ONTAP y StorageGRID. 
---
= Almacenamiento compatible en Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Keystone STaaS admite almacenamiento unificado, optimizado por bloques, AFX y de objetos en plataformas NetApp, así como Cloud Volumes ONTAP. Cada tipo de almacenamiento se define como un tipo de almacenamiento de datos (DST) y está disponible con servicios estándar incluidos en la suscripción básica, junto con servicios complementarios opcionales.



== Servicios estándar y adicionales de Keystone STaaS

Keystone STaaS proporciona servicios estándar y opcionales para su almacenamiento.

*Servicios estándar Keystone STaaS*: Los servicios estándar están incluidos dentro de la suscripción básica y no se cobran por separado.

*Servicios complementarios de Keystone STaaS*: Estos son servicios opcionales que se pueden cargar y que proporcionan utilidades y beneficios adicionales además de los servicios de suscripción estándar de Keystone STaaS.

Puedes suscribirte a varios servicios Keystone STaaS al mismo tiempo. Cuando se añaden servicios en la nube a una suscripción, comparten el mismo plazo que el almacenamiento unificado, optimizado por bloques y/o por objetos. Se puede añadir un servicio en la nube en cualquier momento durante una suscripción de almacenamiento activa. Sin embargo, si no planeas renovar una suscripción existente de almacenamiento unificado, optimizado por bloques o por objetos, no se puede añadir un servicio en la nube durante los últimos 90 días de esa suscripción.


NOTE: Una suscripción AFX es independiente y no puede combinarse con almacenamiento unificado, optimizado para bloques u objetos en la misma suscripción. Si necesitas AFX junto con otros tipos de almacenamiento, debes solicitarlos como suscripciones independientes.



== Tipos de almacenamiento de datos compatibles

Los servicios Keystone STaaS para almacenamiento unificado, optimizado por bloques, de objetos y AFX, son compatibles con múltiples funciones y protocolos, y se describen en la siguiente tabla:

|===
| Tipo de almacenamiento de datos | Descripción | Plataforma | Protocolos | Funciones admitidas 


 a| 
Unificado
 a| 
Incluye almacenamiento de archivos, bloques y objetos S3
 a| 
ONTAP en sistemas AFF y FAS
 a| 
FC, iSCSI, NFS, NFSv4/RDMA, NVMe/FC, NVMe/TCP, SMB, S3
 a| 
Admite todas las funciones de ONTAP One



 a| 
Optimizado para bloques
 a| 
Incluye almacenamiento en bloque
 a| 
NVMe/TCP, NVMe/FC, FC, iSCSI
 a| 
FC e iSCSI
 a| 
Compatible con todas las funciones de ONTAP One for SAN



 a| 
AFX
 a| 
Incluye almacenamiento de archivos y objetos en una plataforma de almacenamiento desagregado
 a| 
ONTAP en sistemas AFX
 a| 
NFSv3, NFSv4/RDMA, pNFS, SMB, S3
 a| 
Admite todas las funciones de ONTAP One



 a| 
Objeto
 a| 
Incluye almacenamiento de objetos
 a| 
StorageGRID
 a| 
S3
 a| 
Compatible con todas las funciones de StorageGRID

|===
Para obtener más información sobre ONTAP One, consulte link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Información general de las licencias de ONTAP"^] y link:https://www.netapp.com/blog/ontap-one/["ONTAP One: Todo el poder de ONTAP, ahora todo en uno"^] .



== Servicios para almacenamiento en cloud

Keystone STaaS proporciona servicios de almacenamiento en cloud. Keystone STaaS admite funcionalidades de gestión de datos Cloud Volumes ONTAP en Amazon Web Services (AWS), Microsoft Azure y Google Cloud Platform.


NOTE: Los servicios de computación, almacenamiento y red basados en hiperescalador que requiere Cloud Volumes ONTAP no son proporcionados por NetApp como parte de las suscripciones a Keystone STaaS; estas suscripciones deben adquirirse directamente de los proveedores de servicios en la nube de hiperescalador.
