---
sidebar: sidebar 
permalink: installation/addl-req.html 
keywords: keystone unified manager prerequisites, aiqum config keystone 
summary: requisitos previos del administrador unificado keystone 
---
= Requisitos previos adicionales para ONTAP y StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Debe completar algunos requisitos previos adicionales de ONTAP y StorageGRID. Asegúrese de completar estos requisitos previos específicos además de los requisitos del sistema Linux/VMware vSphere. Haga clic en la pestaña necesaria para obtener más información.

[role="tabbed-block"]
====
.ONTAP
--
Para la instalación de Keystone Collector en ONTAP, realice estos pasos como requisitos previos:

. Compruebe que un servidor de Active IQ Unified Manager (Unified Manager) esté configurado con Unified Manager 9.7 o una versión posterior. Para obtener información sobre la instalación de Unified Manager, consulte estos enlaces:
+
** https://["Instalación de Unified Manager en sistemas VMware vSphere"^]
** https://["Instalación de Unified Manager en sistemas Linux"^]


. Compruebe que el clúster de ONTAP se haya añadido a Unified Manager. Para obtener información sobre cómo añadir clústeres, consulte https://["Añadir clústeres"^].
. Cree usuarios de Unified Manager con roles específicos para la recogida de datos de uso y rendimiento. Siga estos pasos. Para obtener más información sobre los roles de usuario, consulte https://["Definiciones de roles de usuario"^].
+
.. Inicie sesión en la interfaz de usuario web de Unified Manager con las credenciales de usuario del administrador de aplicaciones predeterminadas que se generan durante la instalación. Consulte https://["Acceder a la interfaz de usuario web de Unified Manager"^].
.. Cree una cuenta de servicio para Keystone Collector con `Operator` rol de usuario. Las API de servicio de Keystone Collector utilizan esta cuenta de servicio para comunicarse con Unified Manager y recopilar datos de uso. Consulte https://["Adición de usuarios"^].
.. Cree un `Database` cuenta de usuario, con la `Report Schema` función. Este usuario es necesario para la recopilación de datos de rendimiento. Consulte https://["Creación de un usuario de base de datos"^].


. Habilite la puerta de enlace API en Unified Manager. Keystone Collector utiliza la función API Gateway para comunicarse con clústeres ONTAP. Puede habilitar la puerta de enlace API desde la interfaz de usuario web o mediante la ejecución de algunos comandos a través de la CLI de Unified Manager.
+
.Interfaz de usuario web de
Para habilitar la puerta de enlace de la API desde la interfaz de usuario web de Unified Manager, inicie sesión en la interfaz de usuario web de Unified Manager y habilite API Gateway. Para obtener más información, consulte https://["Habilitar API Gateway"^].

+
.CLI
Para habilitar la puerta de enlace de API mediante la CLI de Unified Manager, siga estos pasos:

+
.. En Unified Manager Server, inicie una sesión SSH e inicie sesión en la CLI de Unified Manager.
`um cli login -u _<umadmin>_`Para obtener más información acerca de los comandos de la CLI, consulte https://["Comandos de CLI de Unified Manager compatibles"^].
.. Compruebe si la puerta de enlace API ya está activada.
`um option list api.gateway.enabled`A. `true` El valor indica que la puerta de enlace API está habilitada.
.. Si el valor devuelto es `false`, ejecute este comando:
`um option set api.gateway.enabled=true`
.. Reinicie el servidor de Unified Manager:
+
*** Linux: https://["Reiniciar Unified Manager"^].
*** VSphere de VMware: https://["Reiniciar la máquina virtual de Unified Manager"^].






--
.StorageGRID
--
Se requieren las siguientes configuraciones para instalar Keystone Collector en StorageGRID.

* StorageGRID `11.4.0` o se debe instalar una versión posterior. Para obtener más información sobre la actualización de StorageGRID, consulte link:https://docs.netapp.com/us-en/storagegrid-116/upgrade/index.html["Actualizar el software StorageGRID: Descripción general"^].
* Se debe crear una cuenta de usuario administrador local de StorageGRID para la recopilación de datos de uso. El servicio de Collector de Keystone utiliza esta cuenta de servicio para comunicarse con StorageGRID a través de las API de nodos de administrador.
+
.Pasos
.. Inicie sesión en Grid Manager. Consulte https://["Inicie sesión en Grid Manager"^].
.. Cree un grupo de administración local con `Access mode: Read-only`. Consulte https://["Cree un grupo de administración"^].
.. Añada los siguientes permisos:
+
*** Cuentas de inquilino
*** Mantenimiento
*** Consulta de métricas


.. Cree un usuario de cuenta de servicio de Keystone y asócielo con el grupo de administración. Consulte https://["Gestionar usuarios"].




--
====