---
sidebar: sidebar 
permalink: installation/asup-config.html 
keywords: ASUP, AutoSupport configuration 
summary: Procedimiento para configurar AutoSupport para Keystone 
---
= Configura AutoSupport para Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cuando se utiliza el mecanismo de telemetría AutoSupport, Keystone calcula el uso en función de los datos de telemetría de AutoSupport. Para lograr el nivel de granularidad necesario, debe configurar AutoSupport para incorporar datos de Keystone en los paquetes de soporte diarios que envían los clústeres de ONTAP.

.Acerca de esta tarea
Debe tener en cuenta lo siguiente antes de configurar AutoSupport para que incluya datos de Keystone.

* Puede editar las opciones de telemetría de AutoSupport mediante la CLI de ONTAP. Para obtener más información sobre la gestión de servicios de AutoSupport y el rol de administrador del sistema (clúster), consulte https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["Información general sobre Manage AutoSupport"^] y.. https://docs.netapp.com/us-en/ontap/system-admin/cluster-svm-administrators-concept.html["Administradores de clústeres y SVM"^].
* Incluyes los subsistemas en los paquetes diarios y semanales de AutoSupport para garantizar la recogida de datos precisa para Keystone. Para obtener información sobre los subsistemas de AutoSupport, consulte https://docs.netapp.com/us-en/ontap/system-admin/autosupport-subsystem-collection-reference.html["Qué son los subsistemas AutoSupport"^].


.Pasos
. Como usuario administrador del sistema, inicie sesión en el clúster de Keystone ONTAP mediante SSH. Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html["Acceda al clúster mediante SSH"^].
. Modifique el contenido del log.
+
** Ejecute este comando para modificar el contenido del registro diario:
+
[source]
----
autosupport trigger modify -node * -autosupport-message management.log -basic-additional wafl,nfs,performance,snapshot,platform,object_store_server,san,raid,snapmirror -troubleshooting-additional wafl
----
** Ejecute este comando para modificar el contenido del log semanal:
+
[source]
----
autosupport trigger modify -autosupport-message weekly -troubleshooting-additional wafl -node *
----
+
Para obtener más información acerca de este comando, consulte https://docs.netapp.com/us-en/ontap-cli-9131/system-node-autosupport-trigger-modify.html["modificación del disparador AutoSupport del nodo del sistema"^].




