---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Instale el software Keystone Collector desde el repositorio de software YUM. 
---
= Instale Keystone Collector en sistemas Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede instalar el software Keystone Collector en un servidor Linux usando un RPM o un paquete Debian. Siga los pasos de instalación dependiendo de su distribución de Linux.

[role="tabbed-block"]
====
.Uso de RPM
--
. SSH al servidor de Keystone Collector y vaya a. `root` privilegio.
. Importe la firma pública de Keystone :
`# rpm --import https://keystone.netapp.com/repo1/RPM-GPG-NetApp-Keystone-20251020`
. Asegúrese de que se ha importado el certificado público correcto comprobando la huella digital de Keystone Billing Platform en la base de datos RPM:
`# rpm -qa gpg-pubkey --qf '%{Description}'|gpg --show-keys --fingerprint` La huella dactilar correcta tiene este aspecto:
`9297 0DB6 0867 22E7 7646 E400 4493 5CBB C9E9 FEDC`
. Descarga el `keystonerepo.rpm` archivo:
`curl -O https://keystone.netapp.com/repo1/keystonerepo.rpm`
. Verifique la autenticidad del archivo:
`rpm --checksig -v keystonerepo.rpm` La firma de un archivo auténtico tiene este aspecto:
`Header V4 RSA/SHA512 Signature, key ID c9e9fedc: OK`
. Instale el archivo de repositorio de software YUM:
`# yum install keystonerepo.rpm`
. Cuando se instale Keystone repo, instale el paquete Keystone-collector a través del gestor de paquetes YUM:
+
`# yum install keystone-collector`

+
Para Red Hat Enterprise Linux 9, ejecute el siguiente comando para instalar el paquete keystone-collector: 
`# yum install keystone-collector-rhel9`



--
.Usando Debian
--
. SSH al servidor del recopilador de Keystone y eleva a `root` privilegio.
`sudo su`
. Descargue el `keystone-sw-repo.deb` archivo:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Instale el archivo de repositorio del software de Keystone:
`# dpkg -i keystone-sw-repo.deb`
. Actualice la lista de paquetes:
`# apt-get update`
. Cuando se instale el repositorio de Keystone, instale el paquete keystone-collector:
`# apt-get install keystone-collector`


--
====

NOTE: Al completar la instalación, puede usar la utilidad Keystone Collector Management Terminal User Interface (TUI) para realizar las actividades de configuración y supervisión. Puede usar varios controles del teclado, como las teclas Entrar y flecha, para seleccionar las opciones y navegar por esta TUI. Consulte link:../installation/configuration.html["Configure Keystone Collector"] y.. link:../installation/monitor-health.html["Supervise el estado del sistema"] para obtener más información.
