---
sidebar: sidebar 
permalink: installation/linux-installation.html 
keywords: Linux installation Keystone, Linux Collector installation 
summary: Instale el software Keystone Collector desde el repositorio de software YUM. 
---
= Instale Keystone Collector en sistemas Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Puede instalar el software Keystone Collector en un servidor Linux usando un RPM o un paquete Debian. Siga los pasos de instalación dependiendo de su distribución de Linux.

[role="tabbed-block"]
====
.Uso de RPM
--
. SSH al servidor de Keystone Collector y vaya a. `root` privilegio.
. Importe la firma de firma pública de Keystone:
`# rpm --import https://keystone.netapp.com/repo/RPM-GPG-NetApp-Keystone-20221101`
. Asegúrese de importar el certificado público correcto comprobando la huella digital de la plataforma de facturación Keystone en la base de datos RPM:
`# rpm -qa gpg-pubkey --qf '%_<Description>_'|gpg --show-keys --fingerprint`
La huella digital correcta tiene este aspecto:
`90B3 83AF E07B 658A 6058 5B4E 76C2 45E4 33B6 C17D`
. Descargue el `keystonerepo.rpm` archivo:
`curl -O https://keystone.netapp.com/repo/keystonerepo.rpm`
. Verifique la autenticidad del archivo:
`rpm --checksig -v keystonerepo.rpm`Una firma para un archivo auténtico tiene este aspecto:
`Header V4 RSA/SHA512 Signature, key ID 33b6c17d: OK`
. Instale el archivo de repositorio de software YUM:
`# yum install keystonerepo.rpm`
. Cuando se instale Keystone repo, instale el paquete Keystone-collector a través del gestor de paquetes YUM:
`# yum install keystone-collector`


--
.Usando Debian
--
. SSH al servidor del recopilador de Keystone y eleva a `root` privilegio.
`sudo su`
. Descargue el `keystone-sw-repo.deb` archivo:
`curl -O https://keystone.netapp.com/downloads/keystone-sw-repo.deb`
. Instale el archivo de repositorio del software de Keystone:
`# dpkg -i keystone-sw-repo.deb`
. Actualice la lista de paquetes:
`# apt-get update`
. Cuando se instale el repositorio de Keystone, instale el paquete keystone-collector:
`# apt-get install keystone-collector`


--
====

NOTE: Al completar la instalación, puede usar la utilidad Keystone Collector Management Terminal User Interface (TUI) para realizar las actividades de configuración y supervisión. Puede usar varios controles del teclado, como las teclas Entrar y flecha, para seleccionar las opciones y navegar por esta TUI. Consulte link:../installation/configuration.html["Configure Keystone Collector"] y.. link:../installation/monitor-health.html["Supervise el estado del sistema"] para obtener más información.
