---
sidebar: sidebar 
permalink: installation/linux-prereqs.html 
keywords: prerequisites, Linux 
summary: Requisitos previos para la instalación del recopilador Keystone en sistemas Linux 
---
= Requisitos del sistema Linux
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La preparación de su sistema Linux con el software necesario garantiza una instalación precisa y la recopilación de datos por parte de Keystone Collector.

Asegúrese de que su máquina virtual del servidor de recopilador de Linux y Keystone tenga estas configuraciones.

.Servidor Linux:
* Sistema operativo: CentOS 7 o Red Hat Enterprise Linux 8.6 o posterior
* Hora cronyd sincronizada
* Acceso a los repositorios de software estándar de Linux


El mismo servidor también debería tener los siguientes paquetes de terceros:

* Podman (POD Manager)
* sos
* crony
* python 3 (3.6.8 a 3.9.13)


.Máquina virtual del servidor de recopilador Keystone:
* Básico: 2 CPU
* RAM: 4 GB DE RAM
* Espacio en disco: 50 GB vDisk




== Otros requisitos

Asegúrese de que se cumplen los siguientes requisitos genéricos:



=== Requisitos de red

Los requisitos de red de Keystone Collector se enumeran en la siguiente tabla.


NOTE: Keystone Collector requiere conexión a Internet. Puede proporcionar conectividad a Internet mediante enrutamiento directo a través de la puerta de enlace predeterminada (mediante NAT) o mediante el proxy HTTP. Ambas variantes se describen aquí.

|===


| Origen | Destino | Servicio | Protocolo y puertos | Categoría | Específico 


 a| 
Keystone Collector (para Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorio (si se utiliza Keystone ONTAP)
 a| 
Colección de métricas de uso de Keystone Collector para ONTAP



 a| 
Keystone Collector (para Keystone StorageGRID)
 a| 
Nodos de administrador de StorageGRID
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorio (si se utiliza Keystone StorageGRID)
 a| 
Colección de métricas de uso de Keystone Collector para StorageGRID



 a| 
Keystone Collector (genérico)
 a| 
Internet (según los requisitos de URL proporcionados más adelante)
 a| 
HTTPS
 a| 
TCP 80, TCP 443
 a| 
Obligatorio (conexión a Internet)
 a| 
Software Keystone Collector, actualizaciones del sistema operativo y carga de métricas



 a| 
Keystone Collector (genérico)
 a| 
Proxy HTTP del cliente
 a| 
Proxy HTTP
 a| 
Puerto proxy del cliente
 a| 
Obligatorio (conexión a Internet)
 a| 
Software Keystone Collector, actualizaciones del sistema operativo y carga de métricas



 a| 
Keystone Collector (genérico)
 a| 
Servidores DNS del cliente
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obligatorio
 a| 
Resolución DNS



 a| 
Keystone Collector (genérico)
 a| 
Servidores NTP del cliente
 a| 
NTP
 a| 
UDP 123
 a| 
Obligatorio
 a| 
Sincronización de la hora



 a| 
Keystone Collector (para Keystone ONTAP)
 a| 
Unified Manager
 a| 
MYSQL
 a| 
TCP 3306
 a| 
Funcionalidad opcional
 a| 
Recopilación de métricas de rendimiento para Keystone Collector



 a| 
Keystone Collector (genérico)
 a| 
Sistema de monitorización del Cliente
 a| 
HTTPS
 a| 
TCP 7777
 a| 
Funcionalidad opcional
 a| 
Informes de estado de Keystone Collector



 a| 
Estaciones de trabajo de operaciones del cliente
 a| 
Recopilador Keystone
 a| 
SSH
 a| 
TCP 22
 a| 
Gestión
 a| 
Acceso a Keystone Collector Management



 a| 
Direcciones de gestión de nodos y clústeres ONTAP de NetApp
 a| 
Recopilador Keystone
 a| 
HTTP_8000, PING
 a| 
TCP 8000, ICMP Echo Request/Reply
 a| 
Funcionalidad opcional
 a| 
Servidor web para actualizaciones de firmware de ONTAP

|===


=== Acceso a URL

Keystone Collector necesita acceder a los siguientes hosts de Internet:

|===


| Dirección | Razón 


 a| 
https://keystone.netapp.com[]
 a| 
Informes de uso y actualizaciones del software Keystone Collector



 a| 
https://support.netapp.com[]
 a| 
Sede central de NetApp para la información de facturación y entrega de AutoSupport

|===