---
sidebar: sidebar 
permalink: installation/vapp-prereqs.html 
keywords: prerequisites, VMware vSphere, vApp 
summary: Requisitos previos para instalar el recopilador Keystone en sistemas VMware vSphere 
---
= Requisitos de infraestructura virtual
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se necesitan algunas configuraciones de infraestructura virtual para instalar Keystone Collector en sus sistemas VMware vSphere.

.Requisitos previos para la máquina virtual del servidor de recopilador de Keystone:
* Sistema operativo: VMware vCenter Server y ESXi 6.5 o posterior
* Básico: 4 CPU
* RAM: 12 GB DE RAM
* Espacio en disco: 200 GB vDisk




== Otros requisitos

Asegúrese de que se cumplen los siguientes requisitos genéricos:



=== Requisitos de red

Los requisitos de red de Keystone Collector se enumeran en la siguiente tabla.


NOTE: Keystone Collector requiere conexión a Internet. Puede proporcionar conectividad a Internet mediante enrutamiento directo a través de la puerta de enlace predeterminada (mediante NAT) o mediante el proxy HTTP. Ambas variantes se describen aquí.

|===


| Origen | Destino | Servicio | Protocolo y puertos | Categoría | Específico 


 a| 
Keystone Collector (para Keystone ONTAP)
 a| 
Active IQ Unified Manager (Unified Manager)
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorio (si se utiliza Keystone ONTAP)
 a| 
Colección de métricas de uso de Keystone Collector para ONTAP



 a| 
Keystone Collector (para Keystone StorageGRID)
 a| 
Nodos de administrador de StorageGRID
 a| 
HTTPS
 a| 
TCP 443
 a| 
Obligatorio (si se utiliza Keystone StorageGRID)
 a| 
Colección de métricas de uso de Keystone Collector para StorageGRID



 a| 
Keystone Collector (genérico)
 a| 
Internet (según los requisitos de URL proporcionados más adelante)
 a| 
HTTP Y HTTPS
 a| 
TCP 80, TCP 443
 a| 
Obligatorio (conexión a Internet)
 a| 
Software Keystone Collector, actualizaciones del sistema operativo y carga de métricas



 a| 
Keystone Collector (genérico)
 a| 
Proxy HTTP del cliente
 a| 
Proxy HTTP
 a| 
Puerto proxy del cliente
 a| 
Obligatorio (conexión a Internet)
 a| 
Software Keystone Collector, actualizaciones del sistema operativo y carga de métricas



 a| 
Keystone Collector (genérico)
 a| 
Servidores DNS del cliente
 a| 
DNS
 a| 
TCP/UDP 53
 a| 
Obligatorio
 a| 
Resolución DNS



 a| 
Keystone Collector (genérico)
 a| 
Servidores NTP del cliente
 a| 
NTP
 a| 
UDP 123
 a| 
Obligatorio
 a| 
Sincronización de la hora



 a| 
Keystone Collector (para Keystone ONTAP)
 a| 
Unified Manager
 a| 
MYSQL
 a| 
TCP 3306
 a| 
Funcionalidad opcional
 a| 
Recopilación de métricas de rendimiento para Keystone Collector



 a| 
Keystone Collector (genérico)
 a| 
Sistema de monitorización del Cliente
 a| 
HTTP
 a| 
TCP 777
 a| 
Funcionalidad opcional
 a| 
Informes de estado de Keystone Collector



 a| 
Estaciones de trabajo de operaciones del cliente
 a| 
Recopilador Keystone
 a| 
SSH
 a| 
TCP 22
 a| 
Gestión
 a| 
Acceso a Keystone Collector Management



 a| 
Direcciones de gestión de nodos y clústeres ONTAP de NetApp
 a| 
Recopilador Keystone
 a| 
HTTP_8000, PING
 a| 
TCP 8000, ICMP Echo Request/Reply
 a| 
Funcionalidad opcional
 a| 
Servidor web para actualizaciones de firmware de ONTAP

|===


=== Acceso a URL

Keystone Collector necesita acceder a los siguientes hosts de Internet:

|===


| Dirección | Razón 


 a| 
https://keystone.netapp.com[]
 a| 
Informes de uso y actualizaciones del software Keystone Collector



 a| 
https://support.netapp.com[]
 a| 
Sede central de NetApp para la información de facturación y entrega de AutoSupport



 a| 
http://mirror.centos.org[]
http://mirrorlist.centos.org[]
 a| 
Actualizaciones del sistema operativo para Keystone Collector (solo puestas en marcha de OVA)



 a| 
https://repo.mysql.com[]
 a| 
Descargar y actualizar dependencias de MySQL (solo para implementaciones de Linux)

|===