---
sidebar: sidebar 
permalink: release-notes/fixed-issues.html 
keywords: fixed issues 
summary: Problemas solucionados en diferentes versiones de STaaS de Keystone 
---
= Problemas solucionados
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los problemas encontrados en versiones anteriores de los servicios de STaaS de NetApp Keystone se han solucionado en versiones posteriores. Estas son las correcciones.

[cols="3*"]
|===
| Descripción del problema | Después de la corrección | Corregido en versión 


 a| 
La colocación incorrecta de los datos de Keystone en CSV informa si la columna *Nombre de cuenta* en los informes CSV, generada desde la pestaña *Tendencia de capacidad*, incluye un nombre de cuenta con una coma `(,)`.
 a| 
Los datos de Keystone se alinean correctamente en los informes de volúmenes compartidos en clúster.
 a| 
29 de mayo de 2024



 a| 
Muestra el uso de ráfaga acumulado desde la pestaña *Tendencia de capacidad* incluso si el consumo está por debajo de la capacidad comprometida.
 a| 
Fija
 a| 
29 de mayo de 2024



 a| 
Texto de información sobre herramientas incorrecto para el icono de índice *Current Burst* en la pestaña *Capacity Trend*.
 a| 
Muestra el texto correcto sobre herramientas «_La cantidad de capacidad aumentada que se está consumiendo actualmente. Tenga en cuenta que esto es para el período de facturación actual, no para el rango de fechas seleccionado.
 a| 
28 de marzo de 2024



 a| 
La información sobre los volúmenes no conformes a la normativa AQoS y los partners MetroCluster no está disponible para las suscripciones de AutoSupport si los datos de Keystone no están presentes durante 24 horas.
 a| 
Fija
 a| 
28 de marzo de 2024



 a| 
Discrepancia ocasional en el número de volúmenes no compatibles con AQoS enumerados en las pestañas *Resumen de volumen* y *Detalles de volumen* si hay dos niveles de servicio asignados a un volumen que cumple con el cumplimiento de AQoS solo para un nivel de servicio.
 a| 
Fija
 a| 
28 de marzo de 2024



 a| 
No hay información disponible en la pestaña *Activos* para suscripciones a AutoSupport.
 a| 
Fija
 a| 
14 de marzo de 2024



 a| 
Si MetroCluster y FabricPool se habilitaran en un entorno en el que los planes de tarifas tanto para la organización en niveles como para el almacenamiento de objetos fueran aplicables, los niveles de servicio podrían derivarse incorrectamente para los volúmenes de mirroring (en los volúmenes de componentes y FabricPool).
 a| 
Los niveles de servicio correctos se aplican a los volúmenes de reflejo.
 a| 
29 de febrero de 2024



 a| 
Para algunas suscripciones que tienen un único nivel de servicio o plan de tarifas, la columna de cumplimiento de AQoS faltaba en la salida CSV de los informes de la pestaña *volúmenes*.
 a| 
La columna de cumplimiento está visible en los informes.
 a| 
29 de febrero de 2024



 a| 
En algunos entornos MetroCluster, se detectó una anomalía ocasional en los gráficos de densidad de IOPS de la pestaña *Rendimiento*. Esto se debía a una asignación imprecisa de volúmenes a niveles de servicio.
 a| 
Los gráficos se muestran correctamente.
 a| 
29 de febrero de 2024



 a| 
El indicador de uso de un registro de consumo de ráfaga se mostraba en ámbar.
 a| 
El indicador aparece en rojo.
 a| 
13 de diciembre de 2023



 a| 
El intervalo de fechas y los datos de las pestañas Tendencia de capacidad, Uso actual y Rendimiento no se convirtieron a la zona horaria UTC.
 a| 
El rango de fechas para la consulta y los datos en todas las pestañas se muestran en la hora UTC (zona horaria del servidor). La zona horaria UTC también se muestra en cada campo de fecha de las pestañas.
 a| 
13 de diciembre de 2023



 a| 
Se ha producido una discrepancia entre la fecha de inicio y la fecha de finalización entre las pestañas y los informes CSV descargados.
 a| 
Fija.
 a| 
13 de diciembre de 2023

|===