---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Los problemas conocidos identifican problemas que podrían impedirle utilizar Keystone de manera eficaz. 
---
= Problemas conocidos en STaaS de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los problemas conocidos identifican problemas que podrían impedirle utilizar Keystone STaaS de manera eficaz.

En STaaS de NetApp Keystone se notifican los siguientes problemas conocidos:

[cols="3*"]
|===
| Problema conocido | Descripción | Solución alternativa 


 a| 
Modificar suscripción no disponible
 a| 
La opción de modificar la capacidad comprometida para las suscripciones de Keystone actualmente no está disponible en la NetApp Console. Esta funcionalidad se volverá a incluir en una próxima versión.
 a| 
Ninguno



 a| 
Factura incorrecta debido a que los datos no coinciden
 a| 
Una discrepancia en los datos de consumo para las suscripciones de AutoSupport provoca la generación de facturas incorrectas, lo que provoca imprecisiones en la facturación.
 a| 
Ninguno



 a| 
Se muestra un tipo de política de calidad de servicio incorrecto
 a| 
En la pestaña *Detalles de volumen*, la columna *Tipo de política de QoS* muestra _QoS_ cuando no se aplica ninguna política de QoS, y la columna Compatible muestra _NOT SET_, lo que provoca una inconsistencia en el estado de la política de QoS mostrado.
 a| 
Ninguno



 a| 
Los detalles de volumen no están disponibles para las suscripciones principales y vinculadas
 a| 
La pestaña *Volume Summary* muestra cero para el número total de volúmenes, el estado de cumplimiento de QoS, el recuento de volúmenes protegidos y la capacidad total consumida para suscripciones primarias y secundarias vinculadas.
 a| 
Ninguno

|===