---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Los problemas conocidos identifican problemas que pueden impedirle usar de forma efectiva los servicios de suscripción de Keystone. 
---
= Problemas conocidos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Los problemas conocidos identifican problemas que pueden impedirle usar de forma efectiva los servicios de suscripción de Keystone.

En STaaS de NetApp Keystone se notifican los siguientes problemas conocidos:

[cols="3*"]
|===
| Problema conocido | Descripción | Solución alternativa 


 a| 
Se muestra un tipo de política de calidad de servicio incorrecto
 a| 
En la pestaña *Detalles de volumen*, la columna *Tipo de política de QoS* muestra _QoS_ cuando no se aplica ninguna política de QoS, y la columna Compatible muestra _NOT SET_, lo que provoca una inconsistencia en el estado de la política de QoS mostrado.
 a| 
Ninguno



 a| 
Los detalles de volumen no están disponibles para las suscripciones principales y vinculadas
 a| 
La pestaña *Volume Summary* muestra cero para el número total de volúmenes, el estado de cumplimiento de QoS, el recuento de volúmenes protegidos y la capacidad total consumida para suscripciones primarias y secundarias vinculadas.
 a| 
Ninguno

|===