---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: netapp, keystone, release notes, known issues 
summary: Problemas conocidos en el motor de servicio de NetApp 
---
= Problemas conocidos en el motor de servicio de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El siguiente problema conocido se ha notificado en STaaS de NetApp Keystone. Es posible que encuentre este problema al aprovisionar o utilizar su almacenamiento como parte de sus suscripciones a Keystone.

[cols="3*"]
|===
| Problema conocido | Descripción | Solución alternativa 


 a| 
Nivel de servicio incorrecto derivado para volúmenes de reflejo.
 a| 
Si MetroCluster y FabricPool están habilitados en un entorno en el que los planes de tarifas tanto para la organización en niveles como para el almacenamiento de objetos son aplicables, es posible que los niveles de servicio derivados de los volúmenes de mirroring (tanto volúmenes constituyentes como FabricPool) sean incorrectos.
 a| 
Ninguno.

|===