---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nuevas funciones y mejoras de STaaS de Keystone. 
---
= Novedades en STaaS de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ofrece funciones nuevas y mejoradas en cada lanzamiento de los servicios de STaaS de Keystone.



== Nuevas funciones y mejoras para el 13 de febrero de 2024

El siguiente cambio se ha realizado en la pantalla *Suscripciones Keystone* del asesor digital Active IQ (también conocido como asesor digital).



=== Posibilidad de ver suscripciones vinculadas a una suscripción principal

Algunas de sus suscripciones principales pueden tener suscripciones secundarias vinculadas. Si ese es el caso, el número de suscripción principal seguirá mostrándose en la columna *Número de suscripción*, mientras que los números de suscripción vinculados aparecerán en una nueva columna *Suscripciones vinculadas* en la pestaña *Suscripciones*. La columna *Suscripciones vinculadas* solo estará disponible si tiene suscripciones vinculadas, y podrá ver mensajes informativos que le notifiquen sobre ellas.



== Nuevas funciones y mejoras para el 11 de enero de 2024

Descubra las novedades de esta versión.

Los siguientes cambios se han realizado en la pantalla *Suscripciones Keystone* del Asesor Digital Active IQ (también conocido como Asesor Digital).



=== Datos facturados devueltos para repartición devengada

Las etiquetas para *Explosión acumulada* ahora se modifican a *Explosión acumulada facturada* en la pestaña *Tendencia de capacidad*. Al seleccionar esta opción, podrá ver los gráficos mensuales de los datos de ráfaga devengados facturados. Para obtener más información, consulte link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Consulta de repartición devengada facturada"^].



=== Detalles de consumo devengado para planes de tarifas específicos

Si tiene una suscripción que tiene planes de tarifas con capacidad comprometida _cero_, puede ver los detalles del consumo acumulado en la pestaña *Tendencia de capacidad*. Al seleccionar la opción *Consumo devengado facturado*, puede ver los gráficos mensuales de los datos de consumo devengado facturado.



== Nuevas funciones y mejoras para el 15 de diciembre de 2023

Descubra las novedades de esta versión.



=== Posibilidad de buscar por listas de comprobaciones

La compatibilidad con las listas de comprobaciones del asesor digital de Active IQ (también conocido como asesor digital) se ha ampliado para incluir sistemas Keystone. Ahora puede ver los detalles de las suscripciones para varios clientes mediante la búsqueda con listas de comprobaciones. Para obtener más información sobre el uso de las listas de comprobaciones en STaaS de Keystone, consulte link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Busca mediante listas de comprobaciones de Keystone"^].



=== Fecha convertida a zona horaria UTC

Los datos devueltos en las pestañas de la pantalla *Suscripciones Keystone* del Asesor Digital Active IQ se muestran en la hora UTC (zona horaria del servidor). Al introducir una fecha para la consulta, se considera automáticamente que está en la hora UTC. Para obtener más información, consulte link:../integrations/aiq-keystone-details.html["Panel de suscripción de Keystone e informes"^].
