---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nuevas funciones y mejoras de STaaS de Keystone. 
---
= Novedades en STaaS de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ofrece funciones nuevas y mejoradas en cada lanzamiento de los servicios de STaaS de Keystone.



== Nuevas funciones y mejoras para el 28 de marzo de 2024

La siguiente mejora se ha realizado en la pantalla *Suscripciones Keystone* del Asesor Digital Active IQ (también conocido como Asesor Digital):



=== La mejora del cumplimiento de las políticas de calidad de servicio se muestra en la pestaña Volume Details

La pestaña *Detalles de volumen* de la pestaña *Volúmenes y objetos* ahora proporciona una mejor visibilidad del cumplimiento de la política de calidad de servicio (QoS). La columna anteriormente conocida como *AQoS* se renombró a *Compliant*, que indica si la política QoS cumple. Además, se agrega una nueva columna *QoS Policy Type*, que especifica si la política es fija o adaptativa. Si no se aplica ninguno, la columna muestra _NOT DISPONIBLE_. Para obtener más información, consulte link:../integrations/volumes-objects-tab.html["Volúmenes  ficha Objetos"^].



=== La nueva columna y la suscripción simplificada se muestran en la pestaña Resumen de volumen

* La pestaña *Resumen de volumen* de la pestaña *Volúmenes y objetos* ahora incluye una nueva columna titulada *Protegido*. Esta columna proporciona un recuento de los volúmenes protegidos asociados con los niveles de servicio suscritos. Si haces clic en el número de volúmenes protegidos, te lleva a la pestaña *Detalles del volumen*, donde puedes ver una lista filtrada de volúmenes protegidos.
* La pestaña *Resumen de volumen* se actualiza para mostrar solo las suscripciones básicas, excluyendo los servicios complementarios. Para obtener más información, consulte link:../integrations/volumes-objects-tab.html["Volúmenes  ficha Objetos"^].




=== Cambie a la visualización de detalles de ráfaga acumulada en la pestaña Tendencia de capacidad

La información sobre herramientas que aparece al pasar el cursor sobre el gráfico de barras de uso de capacidad en la pestaña *Tendencia de capacidad* mostrará los detalles de las ráfagas acumuladas para el mes actual. Los detalles no estarán disponibles durante los meses anteriores.



=== Acceso mejorado para ver datos históricos de suscripciones a Keystone

Ahora puedes ver los datos históricos si se modifica o renueva una suscripción de Keystone. Puede establecer la fecha de inicio de una suscripción en una fecha anterior para ver :

* Consumo y datos de uso de ráfaga acumulados de la pestaña *Capacity Trend*,
* Métricas de rendimiento de los volúmenes de ONTAP desde la pestaña *Rendimiento*,


todos los cuales muestran los datos basados en la fecha seleccionada de la suscripción.



== Nuevas funciones y mejoras para el 29 de febrero de 2024

Se han realizado varias mejoras en el panel del asesor digital de Active IQ (también conocido como asesor digital) y en la pantalla *Suscripciones de Keystone* para esta versión:



=== Adición de la pestaña Activos

La pantalla *Suscripciones Keystone* ahora incluye la pestaña *Activos*. Esta nueva pestaña proporciona información a nivel de clúster basada en sus suscripciones. Para obtener más información, consulte link:../integrations/assets-tab.html["Activos"^].



=== Mejoras en la pestaña Volumes & Objects

Para proporcionar una mayor claridad a los volúmenes de su sistema ONTAP, se han añadido dos nuevos botones de pestañas, *Resumen de volumen* y *Detalles de volumen* a la pestaña *Volúmenes*. La pestaña *Resumen de volumen* proporciona un recuento general de los volúmenes asociados con los niveles de servicio suscritos, incluido su estado de cumplimiento de AQoS e información de capacidad. La pestaña *Detalles del volumen* muestra todos los volúmenes y sus detalles. Para obtener más información, consulte link:../integrations/volumes-objects-tab.html["Volúmenes  ficha Objetos"^].



=== Experiencia de búsqueda mejorada en Digital Advisor

Los parámetros de búsqueda en la pantalla de *Digital Advisor* ahora incluyen números de suscripción de Keystone y listas de comprobaciones creadas para suscripciones de Keystone. Puede introducir los tres primeros caracteres de un número de suscripción o nombre de lista de seguimiento. Para obtener más información, consulte link:../integrations/keystone-aiq.html["Consulta el panel de Keystone en el asesor digital de Active IQ"^].



=== Ver registro de hora de los datos de consumo

Puede ver la marca de tiempo de los datos de consumo (en UTC) en el panel antiguo del widget *Suscripciones Keystone*.



== Nuevas funciones y mejoras para el 13 de febrero de 2024

La siguiente mejora se ha realizado en la pantalla *Suscripciones Keystone* del Asesor Digital Active IQ (también conocido como Asesor Digital).



=== Posibilidad de ver suscripciones vinculadas a una suscripción principal

Algunas de sus suscripciones principales pueden tener suscripciones secundarias vinculadas. Si ese es el caso, el número de suscripción principal seguirá mostrándose en la columna *Número de suscripción*, mientras que los números de suscripción vinculados aparecerán en una nueva columna *Suscripciones vinculadas* en la pestaña *Suscripciones*. La columna *Suscripciones vinculadas* solo estará disponible si tiene suscripciones vinculadas, y podrá ver mensajes informativos que le notifiquen sobre ellas.



== Nuevas funciones y mejoras para el 11 de enero de 2024

Descubra las novedades de esta versión.

Las siguientes mejoras se han realizado en la pantalla *Suscripciones Keystone* del asesor digital Active IQ (también conocido como asesor digital).



=== Datos facturados devueltos para repartición devengada

Las etiquetas para *Explosión acumulada* ahora se modifican a *Explosión acumulada facturada* en la pestaña *Tendencia de capacidad*. Al seleccionar esta opción, podrá ver los gráficos mensuales de los datos de ráfaga devengados facturados. Para obtener más información, consulte link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Consulta de repartición devengada facturada"^].



=== Detalles de consumo devengado para planes de tarifas específicos

Si tiene una suscripción que tiene planes de tarifas con capacidad comprometida _cero_, puede ver los detalles del consumo acumulado en la pestaña *Tendencia de capacidad*. Al seleccionar la opción *Consumo devengado facturado*, puede ver los gráficos mensuales de los datos de consumo devengado facturado.



== Nuevas funciones y mejoras para el 15 de diciembre de 2023

Descubra las novedades de esta versión.



=== Posibilidad de buscar por listas de comprobaciones

La compatibilidad con las listas de comprobaciones del asesor digital de Active IQ (también conocido como asesor digital) se ha ampliado para incluir sistemas Keystone. Ahora puede ver los detalles de las suscripciones para varios clientes mediante la búsqueda con listas de comprobaciones. Para obtener más información sobre el uso de las listas de comprobaciones en STaaS de Keystone, consulte link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Busca mediante listas de comprobaciones de Keystone"^].



=== Fecha convertida a zona horaria UTC

Los datos devueltos en las pestañas de la pantalla *Suscripciones Keystone* del Asesor Digital Active IQ se muestran en la hora UTC (zona horaria del servidor). Al introducir una fecha para la consulta, se considera automáticamente que está en la hora UTC. Para obtener más información, consulte link:../integrations/aiq-keystone-details.html["Panel de suscripción de Keystone e informes"^].
