---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'new features, release notes, enhancements, what"s new' 
summary: Nuevas funciones y mejoras de STaaS de Keystone. 
---
= Novedades en STaaS de Keystone
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ofrece funciones nuevas y mejoradas en cada lanzamiento de los servicios de STaaS de Keystone.

Las siguientes mejoras se introducen en la pantalla *Suscripciones Keystone* del asesor digital Active IQ (también conocido como asesor digital):



== 27 de junio de 2024



=== Visualización consistente de la suscripción

La pantalla *Suscripciones Keystone* se actualiza para mostrar el número de suscripción seleccionado en todas las pestañas.

* Cuando se actualiza cualquier pestaña dentro de la pantalla *Suscripciones Keystone*, la pantalla navega automáticamente a la pestaña *Suscripciones* y restablece todas las pestañas a la primera suscripción que aparece en la lista desplegable *Suscripción*.
* Si la suscripción seleccionada no está suscrita a métricas de rendimiento, la pestaña *Rendimiento* mostrará la primera suscripción que aparece en el menú desplegable *Suscripción* al navegar.




== 29 de mayo de 2024



=== Indicador de ráfaga mejorado

El indicador *Burst* en el índice del gráfico de uso se mejora para mostrar el valor porcentual del límite de ráfaga. Este valor cambia en función del límite de ráfaga acordado para una suscripción. También puede ver el valor del límite de ráfaga en la pestaña *Suscripciones* pasando el cursor sobre el indicador *Uso de ráfaga* en la columna *Estado de uso*.



=== Adición de niveles de servicio

Los niveles de servicio *CVO Primario* y *CVO Secundario* se incluyen para admitir Cloud Volumes ONTAP para suscripciones que tengan planes de tarifas con capacidad comprometida cero o configurados con un clúster metropolitano.

* Puede ver el gráfico de uso de capacidad para estos niveles de servicio desde el panel antiguo del widget *Suscripciones Keystone* y la pestaña *Tendencia de capacidad*, así como información detallada de uso en la pestaña *Uso actual*.
* En la pestaña *Suscripciones*, estos niveles de servicio se muestran como `CVO (v2)` En la columna *Tipo de uso*, permitiendo la identificación de facturación según estos niveles de servicio.




=== Función de zoom para obtener información en microráfaga

La pestaña *Capacity Trend* ahora incluye una función de zoom-in para ver los detalles de las subidas a corto plazo, conocidas como microexplosiones, en los gráficos de uso. Para obtener más información, consulte link:../integrations/capacity-trend-tab.html["Pestaña Capacity Trend"^].



=== Visualización mejorada de suscripciones

La visualización predeterminada de las suscripciones se mejora para ordenarlas por ID de seguimiento. Las suscripciones en la pestaña *Suscripciones*, incluidas las listas desplegables *Suscripción* y los informes CSV, ahora se mostrarán en función de la secuencia alfabética de las identificaciones de seguimiento, siguiendo el orden de a, A, b, B, etc.



=== Visualización de ráfaga acumulada mejorada

La información sobre herramientas que aparece al pasar el ratón sobre el gráfico de barras de uso de capacidad en la pestaña *Tendencia de capacidad* ahora muestra el tipo de ráfaga acumulada en función de la capacidad comprometida. Se diferencia entre la ráfaga devengada provisional y la facturada, mostrando *Consumo devengado provisional* y *Consumo devengado facturado* para suscripciones con planes de tasa de capacidad comprometida cero, y *Ráfaga devengada provisional* y *Ráfaga devengada facturada* para aquellos con capacidad comprometida distinta de cero.



== 09 de mayo de 2024



=== Nuevas columnas en los informes CSV

Los informes CSV de la pestaña *Tendencia de capacidad* ahora incluyen las columnas *Número de suscripción* y *Nombre de cuenta* para mejorar los detalles.



=== Columna Tipo de uso mejorado

La columna *Tipo de uso* dentro de la pestaña *Suscripciones* se ha mejorado para mostrar los usos lógicos y físicos como valores separados por comas para las suscripciones que cubren los niveles de servicio tanto para el archivo como para el objeto.



=== Acceda a los detalles del almacenamiento de objetos en la pestaña Volume Details

La pestaña *Detalles de volumen* de la pestaña *Volúmenes y objetos* ahora proporciona detalles de almacenamiento de objetos junto con información de volumen para las suscripciones que incluyen niveles de servicio tanto para el archivo como para el objeto. Puede hacer clic en el botón *Detalles de almacenamiento de objetos* dentro de la pestaña *Detalles de volumen* para ver los detalles.



== 28 de marzo de 2024



=== La mejora del cumplimiento de las políticas de calidad de servicio se muestra en la pestaña Volume Details

La pestaña *Detalles de volumen* de la pestaña *Volúmenes y objetos* ahora proporciona una mejor visibilidad del cumplimiento de la política de calidad de servicio (QoS). La columna anteriormente conocida como *AQoS* se renombró a *Compliant*, que indica si la política QoS cumple. Además, se agrega una nueva columna *QoS Policy Type*, que especifica si la política es fija o adaptativa. Si no se aplica ninguno, la columna muestra _NOT DISPONIBLE_. Para obtener más información, consulte link:../integrations/volumes-objects-tab.html["Volúmenes  ficha Objetos"^].



=== La nueva columna y la suscripción simplificada se muestran en la pestaña Resumen de volumen

* La pestaña *Resumen de volumen* de la pestaña *Volúmenes y objetos* ahora incluye una nueva columna titulada *Protegido*. Esta columna proporciona un recuento de los volúmenes protegidos asociados con los niveles de servicio suscritos. Si haces clic en el número de volúmenes protegidos, te lleva a la pestaña *Detalles del volumen*, donde puedes ver una lista filtrada de volúmenes protegidos.
* La pestaña *Resumen de volumen* se actualiza para mostrar solo las suscripciones básicas, excluyendo los servicios complementarios. Para obtener más información, consulte link:../integrations/volumes-objects-tab.html["Volúmenes  ficha Objetos"^].




=== Cambie a la visualización de detalles de ráfaga acumulada en la pestaña Tendencia de capacidad

La información sobre herramientas que aparece al pasar el cursor sobre el gráfico de barras de uso de capacidad en la pestaña *Tendencia de capacidad* mostrará los detalles de las ráfagas acumuladas para el mes actual. Los detalles no estarán disponibles durante los meses anteriores.



=== Acceso mejorado para ver datos históricos de suscripciones a Keystone

Ahora puedes ver los datos históricos si se modifica o renueva una suscripción de Keystone. Puede establecer la fecha de inicio de una suscripción en una fecha anterior para ver :

* Consumo y datos de uso de ráfaga acumulados de la pestaña *Capacity Trend*,
* Métricas de rendimiento de los volúmenes de ONTAP desde la pestaña *Rendimiento*,


todos los cuales muestran los datos basados en la fecha seleccionada de la suscripción.



== 29 de febrero de 2024



=== Adición de la pestaña Activos

La pantalla *Suscripciones Keystone* ahora incluye la pestaña *Activos*. Esta nueva pestaña proporciona información a nivel de clúster basada en sus suscripciones. Para obtener más información, consulte link:../integrations/assets-tab.html["Activos"^].



=== Mejoras en la pestaña Volumes & Objects

Para proporcionar una mayor claridad a los volúmenes de su sistema ONTAP, se han añadido dos nuevos botones de pestañas, *Resumen de volumen* y *Detalles de volumen* a la pestaña *Volúmenes*. La pestaña *Resumen de volumen* proporciona un recuento general de los volúmenes asociados con los niveles de servicio suscritos, incluido su estado de cumplimiento de AQoS e información de capacidad. La pestaña *Detalles del volumen* muestra todos los volúmenes y sus detalles. Para obtener más información, consulte link:../integrations/volumes-objects-tab.html["Volúmenes  ficha Objetos"^].



=== Experiencia de búsqueda mejorada en Digital Advisor

Los parámetros de búsqueda en la pantalla de *Digital Advisor* ahora incluyen números de suscripción de Keystone y listas de comprobaciones creadas para suscripciones de Keystone. Puede introducir los tres primeros caracteres de un número de suscripción o nombre de lista de seguimiento. Para obtener más información, consulte link:../integrations/keystone-aiq.html["Consulta el panel de Keystone en el asesor digital de Active IQ"^].



=== Ver registro de hora de los datos de consumo

Puede ver la marca de tiempo de los datos de consumo (en UTC) en el panel antiguo del widget *Suscripciones Keystone*.



== 13 de febrero de 2024



=== Posibilidad de ver suscripciones vinculadas a una suscripción principal

Algunas de sus suscripciones principales pueden tener suscripciones secundarias vinculadas. Si ese es el caso, el número de suscripción principal seguirá mostrándose en la columna *Número de suscripción*, mientras que los números de suscripción vinculados aparecerán en una nueva columna *Suscripciones vinculadas* en la pestaña *Suscripciones*. La columna *Suscripciones vinculadas* solo estará disponible si tiene suscripciones vinculadas, y podrá ver mensajes informativos que le notifiquen sobre ellas.



== 11 de enero de 2024



=== Datos facturados devueltos para repartición devengada

Las etiquetas para *Explosión acumulada* ahora se modifican a *Explosión acumulada facturada* en la pestaña *Tendencia de capacidad*. Al seleccionar esta opción, podrá ver los gráficos mensuales de los datos de ráfaga devengados facturados. Para obtener más información, consulte link:../integrations/aiq-keystone-details.html#view-invoiced-accrued-burst["Consulta de repartición devengada facturada"^].



=== Detalles de consumo devengado para planes de tarifas específicos

Si tiene una suscripción que tiene planes de tarifas con capacidad comprometida _cero_, puede ver los detalles del consumo acumulado en la pestaña *Tendencia de capacidad*. Al seleccionar la opción *Consumo devengado facturado*, puede ver los gráficos mensuales de los datos de consumo devengado facturado.



== 15 de diciembre de 2023



=== Posibilidad de buscar por listas de comprobaciones

Se ha ampliado la compatibilidad con las listas de comprobaciones del asesor digital para incluir los sistemas Keystone. Ahora puede ver los detalles de las suscripciones para varios clientes mediante la búsqueda con listas de comprobaciones. Para obtener más información sobre el uso de las listas de comprobaciones en STaaS de Keystone, consulte link:../integrations/keystone-aiq.html#search-by-using-keystone-watchlists["Busca mediante listas de comprobaciones de Keystone"^].



=== Fecha convertida a zona horaria UTC

Los datos devueltos en las pestañas de la pantalla *Suscripciones Keystone* del Asesor Digital se muestran en la hora UTC (zona horaria del servidor). Al introducir una fecha para la consulta, se considera automáticamente que está en la hora UTC. Para obtener más información, consulte link:../integrations/aiq-keystone-details.html["Panel de suscripción de Keystone e informes"^].
